### ISSUE TITLE
Catch pipeline crashes and report error

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1001]
Servo will soon catch crashes in iframes and report the crash with a mozbrowser event.

See https://github.com/servo/servo/issues/10334

We need to do something about this in browserhtml.

**Comment by paulrouget** [comment]
See: https://github.com/servo/servo/pull/10931 and https://github.com/servo/servo/pull/10551

**Comment by paulrouget** [comment]
To simulate a crash, we can use `--random-pipeline-closure-probability 0.3` (crash with a pipeline with a probability of 0.3).

We get a `mozbrowsererror` event from the iframes. It's supposed to have a `fatal` type, but that's not working yet (see https://github.com/servo/servo/issues/11152). But Servo only report `mozbrowsererror` for crashes so far, so it's always a fatal error.

`event.detail.description` has a summary of the crash and `event.detail.report` includes the backtrace.

We are also supposed to get a `mozbrowsererror` event from the top level window when we get a crash from an unknown location. I don't know how to test this. @asajeffrey is `--random-pipeline-closure-probability` supposed to trigger this kind of crash as well?

Then - once we got the backtrace, we should allow the user to report it.

I was thinking about using github, but that requires the user to be able to login to github, which is not possible today (it crashes… ironically). Maybe we can send the report to a mozilla webservice that doesn't require any login. Maybe we can copy the report the clipboard. Maybe we can open github in another browser. Not sure yet.

Any idea?

/cc @Gozala @metajack @tschneidereit

**Comment by tschneidereit** [comment]
> I was thinking about using github, but that requires the user to be able to login to github, which is not possible today (it crashes… ironically). Maybe we can send the report to a mozilla webservice that doesn't require any login. Maybe we can copy the report to the clipboard. Maybe we can open github in another browser. Not sure yet.

We had that problem in Shumway. I built an [issue reporter](https://github.com/tschneidereit/Shumway-Issue-Reporter) that sent the reports to a server that I had set up. In the end we didn't use that for long because, even though I had gone to some lengths to not include sensitive information, there were privacy concerns. Essentially, whenever we collect user data, we need to involve data stewards in some way, IIUC.

**Comment by asajeffrey** [comment]
At the moment there's no way to test crashes from random threads, just ones attached to a pipeline.

**Comment by paulrouget** [comment]
`type=fatal` works now.

**Comment by asajeffrey** [comment]
#11155 fixed the `type=fatal` problem.

**Comment by paulrouget** [comment]
I think we will go for a simple solution first. We will display the error and offer the user to copy/paste it. Uploading to github or reporting to any other mechanism we might already have in place will happen later.

**Comment by paulrouget** [comment]
I've implemented a new protocol handler in servo that opens http urls in the OS-default web browser. See https://github.com/servo/servo/pull/11286.

So all we need is to get the backtrace, and offer the user to click on a link that looks like this:

exthttps://github.com/servo/servo/issues/new?title=Crash%20report%20from%20browserhtml&body=very%20long%20backtrace

**Comment by nox** [comment]
Btw, could we make a separate repos for the reports? I just remembered arbitrary users can't set labels, so we will have to do all the triage if we want them to mark as user reports or something like that.

**Comment by paulrouget** [comment]
@nox absolutely.
