### ISSUE TITLE
after opening a 2nd tab, CPU rises up

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1002]
Looks a lot like https://github.com/browserhtml/browserhtml/issues/976

/cc @Gozala

**Comment by paulrouget** [comment]
@Gozala any idea what's going on here?

**Comment by paulrouget** [comment]
can someone reproduce? Open a couple of tabs and see if CPU goes up.

**Comment by tschneidereit** [comment]
I don't see this issue, no. Tried with various combinations of tabs and different content in them.

**Comment by paulrouget** [comment]
I'll assign this to me. I need to figure out how to properly reproduce.

**Comment by paulrouget** [comment]
I can't reproduce. I'll re-open if it happens again.
