### ISSUE TITLE
How browser.html scrollbars will be solved?

### ISSUE THREAD

**Issue by lukaszpolowczyk** [browserhtml/browserhtml#1008]
How browser.html scrollbars will be solved?

At this time, Firefox scrollbar is a XUL element. In browser.html there are only pure HTML.

Everyone HTMLElement will have Shadow DOM with the scrollbar?

I was interested because I create extension, and I would like to be able to control this element and not enough to swap colors of buttons. I want to add a scrollbar new features like markers, context menus, extra actions.

**Comment by paulrouget** [comment]
This will need to be implemented in Servo. Afaik, there is no standard to style scrollbars. Webkit implement a `::webkit-scrollbar` pseudo element.

But that won't happen in browserhtml. This is a Servo issue.
