### ISSUE TITLE
pin sidebar doesn't work anymore

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1017]

**Comment by paulrouget** [comment]
might be related: https://github.com/servo/servo/issues/11108

**Comment by paulrouget** [comment]
Doesn't work with Electron either.

@Gozala can you confirm?

**Comment by Gozala** [comment]
Whait what on the contrary, it always works on Electron & actually works in servo as well if non duckduckgo page is active. On duckduckgo I'm just unable to click a button

**Comment by paulrouget** [comment]
Indeed! I works now I've updated master and the modules :)

**Comment by paulrouget** [comment]
ok - so the issue with ddg is interesting. There are 2 bugs here. The page overflows (bug 1) and its overflowing content prevents clicking (bug 2).

I'll investigate.

**Comment by paulrouget** [comment]
Depends on https://github.com/servo/servo/issues/11151

**Comment by Gozala** [comment]
As far as I can tell fix for the mentioned bug resolved this issue. Closing, reopen if you still see it.
