### ISSUE TITLE
Move + and < buttons to toolbar

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1027]

**Comment by tschneidereit** [comment]
One obvious concern is that the buttons should be visible when the sidebar is either open or pinned. Can we perhaps use a filter to have them be the inverse color of the background? That way they would always be visible and we wouldn't have to worry about any transitions.

OTOH, inverting the background might not look great depending on the titlebar's content-based color.

**Comment by paulrouget** [comment]
Not sure to understand. The toolbar moves with the tab when it's zooming out. So the button are always against the same background.

**Comment by Gozala** [comment]
Fixed by #1047
