### ISSUE TITLE
Buttons are only clickable after receiving a mouse-over event

### ISSUE THREAD

**Issue by tschneidereit** [browserhtml/browserhtml#1031]
This is somewhat subtle, but prevents effective automation of UI interactions:
If you try clicking a button, the close button in the upper-right corner, say, before moving the mouse over it, it doesn't receive the click event.

STR:
- move the mouse close to, but not over, the `close` button
- cmd-tab-switch to another window
- move the mouse so that it would be over the button
- cmd-tab-switch back to the servo window

In fact, this should probably also trigger a mouse-over event.

I think this might be a Servo issue, but filing it here to track our problems with it.

**Comment by paulrouget** [comment]
Servo keeps track of the mouse coordinate has it receives mouse move events. This probably should be done when it gets the focus as well.

I'll look at this.

**Comment by paulrouget** [comment]
no wait… I'm mistaken… trying to understand what's going on

**Comment by paulrouget** [comment]
ok - I get it. This is what I was saying.

**Comment by paulrouget** [comment]
Hmm, mouse-over would be solved by updating `self.mouse_pos` in ports/glutin/window.rs, but I don't understand why click doesn't work. It doesn't use `mouse_pos`.

**Comment by tschneidereit** [comment]
Yeah, that's roughly what I assumed, and makes sense.

**Comment by paulrouget** [comment]
actually… it does use `mouse_pos`. `Event::MouseInput` (from glutin) should come with a coordinate, or we should trigger a mouse move when servo gets the focus.

**Comment by tschneidereit** [comment]
@paulrouget, it does receive a `click`, actually. Perhaps we also have an issue in browser.html that prevents the click from doing anything useful?

**Comment by paulrouget** [comment]
This is what happens:

- move the mouse over the window, glutin sends new coordinates
- lose focus
- move mouse
- focus is gain
- click
- servo use the latest coordinate from the first step to click

On focus gain, we need to update the coordinates. We don't have this information from glutin though.

**Comment by paulrouget** [comment]
When glutin sends the click, it doesn't come with a coordinate.

**Comment by tschneidereit** [comment]
>
> When glutin sends the click, it doesn't come with a coordinate.
>
Ah, that makes sense.

**Comment by paulrouget** [comment]
https://github.com/servo/servo/issues/11130

**Comment by paulrouget** [comment]
Let me close this in favor of servo/servo#11130
