### ISSUE TITLE
Scrollbar is missing

### ISSUE THREAD

**Issue by perlun** [browserhtml/browserhtml#1036]
Can be seen on web pages such as Wikipedia. Upstream servo issue is this: https://github.com/servo/servo/issues/6182

I guess this cannot be easily fixed without solving it in servo, either by drawing the scrollbars or providing the interface as suggested there.

**Comment by paulrouget** [comment]
Closing this as there's nothing to be done in browserhtml.

**Comment by perlun** [comment]
Fair enough. Do you not think it would make some sense to have an issue open for tracking this? I mean, it is in fact a form of "defect" in browserhtml (even though it's caused by limitations upstream). That's at least how I tend to think about it.

**Comment by paulrouget** [comment]
> Do you not think it would make some sense to have an issue open for tracking this?

That would have made sense if this would have required browserhtml work or would have involved multiple cross-project issues, but here, it's really just about servo supporting scrollbars.

Furthermore, our team is both working on servo and browserhtml, having 2 bugs about the same thing is not helping.

So no need for a top-level or meta bug.

**Comment by perlun** [comment]
> Furthermore, our team is both working on servo and browserhtml, having 2 bugs about the same thing is not helping.

Hehe, fair point. :smile: Forgive my ignorance in this case; I haven't really contributed anything to browserhtml yet (only servo), so apologies for coming in and drawing the wrong conclusions here.
