### ISSUE TITLE
reddit loads for ever in browserhtml

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1037]
Here is a simple html app to run with servo:

`servo -w -b --pref dom.mozbrowser.enabled a.html`

```html
<iframe style="width:700px;height:500px" mozbrowser="true" src=""></iframe>
<script>
  var iframe = document.querySelector("iframe");
  setTimeout(() => {
    iframe.addEventListener("mozbrowserloadstart", () => { console.log("start") });
    iframe.addEventListener("mozbrowserloadend", () => { console.log("end") });
    setTimeout(() => {
      iframe.src = "http://reddit.com"
    }, 1000);
  }, 1000);
</script>
```

We can see that the iframe both loadstart and loadend events.

Now, in browserhtml, loading reddit.com, the loadend event is not caught.
It doesn't happen all the time, but on my laptop, around %50 of the time.

STR:

- `servo -w --pref dom.mozbrowser.enabled http://localhost:6060 2>/dev/null`
- type reddit.com
- wait 10 seconds (at least until the suggestion shows up)
- press enter

**Comment by paulrouget** [comment]
Can someone please try to reproduce?

**Comment by paulrouget** [comment]
Also, use a recent servo build (May 16th).

**Comment by tschneidereit** [comment]
Tried reproducing this about 20x with the current Homebrew build, to no avail.

**Comment by paulrouget** [comment]
Interesting, here Servo fails to send any `https://reddit.com` `loadend` events, and CPU goes crazy.

I have 2 theories:
- ssl issue related to https://github.com/servo/servo/issues/11008#issuecomment-217243111
- CPU is so busy, that the script thread never gets a chance to send the `loadevent`

**Comment by paulrouget** [comment]
Servo bug: https://github.com/servo/servo/issues/11223

**Comment by paulrouget** [comment]
Closing in favor of https://github.com/servo/servo/issues/11223
