### ISSUE TITLE
releasing forcetouch closes the sidebar

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1038]

**Comment by paulrouget** [comment]
This happens because we get a click on the overlay when it's released.

**Comment by paulrouget** [comment]
This doesn't always happen because of a bug in Servo where the iframe get the mouse events before the overlay. See https://github.com/servo/servo/issues/11108

**Comment by Gozala** [comment]
@paulrouget It is assigned to you, does that mean you're going to fix it ? Also should it be a P2 instead ?

**Comment by Gozala** [comment]
This seems to be caused by servo/servo#11664 @paulrouget do you think it can be fixed in servo or should we come up with a workaround ?

**Comment by Gozala** [comment]
Create a workaround #1087 that is not so bad & avoids the issue described here.

**Comment by Gozala** [comment]
was fixed by #1087
