### ISSUE TITLE
Stop rebuilding the entire virtual DOM on every animation frame

### ISSUE THREAD

**Issue by pcwalton** [browserhtml/browserhtml#1042]
It looks like you're rebuilding the entire virtual DOM every animation frame with the `view` calls. There's no way this can possibly be fast enough to hit 60 FPS: I've profiled this and the JS engine time (just in JS!) exceeds 16 ms regularly on my MacBook Pro 2.8 GHz Haswell.

During the tab switch animation, the only thing that ends up changing is a few styles on each tab and Web views stack. Is there some way you can invoke `view()` on *just* those for the animation frame? If that's not possible, can you cache some of the objects in constant data and reuse them instead of rebuilding objects all the time?

cc @Gozala @paulrouget

**Comment by pcwalton** [comment]
@wycats tells me the React solution for this is called `shouldComponentUpdate`.

**Comment by paulrouget** [comment]
That's not supposed to be the case. We're only supposed to rebuild what has changed.

**Comment by paulrouget** [comment]
(we don't use React)

**Comment by paulrouget** [comment]
@pcwalton which version of browserhtml do you use?

**Comment by wycats** [comment]
I think @pcwalton isn't talking about real DOM mutations, but rather rebuilding the Virtual DOM, which can get expensive once your vdom reaches a certain size.

**Comment by paulrouget** [comment]
> I think @pcwalton isn't talking about real DOM mutations, but rather rebuilding the Virtual DOM, which can get expensive once your vdom reaches a certain size.

I know.

**Comment by wycats** [comment]
> We're only supposed to rebuild what has changed

How do you know what changed before you rebuild the vdom? Do you have some kind of pure-function system a la Redux? Or an escape valve like `shouldComponentUpdate` like React?

**Comment by Gozala** [comment]
We do have an optimization in place to reduce amount of vdom that needs to be generated in form of thunk nodes that are equivalent to react's shouldComponentUpdate hook. Thunks are lazy node representations that only get computed during diffing if state from which actual node is generated changed. 

Typed on tiny keyboard

**Comment by Gozala** [comment]
It could be that we do regenerate more than we should / could though. I'll look into it on Monday 

Typed on tiny keyboard

**Comment by Gozala** [comment]
@pcwalton also as @paulrouget suggested try latest master & make sure to update npm deps. We fixed few bugs in the libs that caused GC pauses & few that derailed us from jit

**Comment by paulrouget** [comment]
For the record, I'm updated browserhtml in Servo.

**Comment by paulrouget** [comment]
@pcwalton Here, with a macbook 12", the JS time is around 3ms per requestAnimationFrame during a tab switch. While profiling, during a tab switch, I see 24% spent in the script thread.

I'm wondering if you've been using an old version of browserhtml.

Also - we believe we can do better, but we decided that was "good enough" until June.

**Comment by paulrouget** [comment]
Correction: mean time in `requestAnimationFrame` 5.18ms.

**Comment by pcwalton** [comment]
Oops. I had a debug SpiderMonkey. I sure feel dumb.
