### ISSUE TITLE
Iframe content is not retained with in the iframe

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1054]
Here is the screenshot illustrating the issue

<img width="834" alt="screen shot 2016-05-31 at 10 41 52 am" src="https://cloud.githubusercontent.com/assets/21236/15686177/f766fa7e-2723-11e6-822e-5ed012c8c2ae.png">

URL loaded in the tab is http://www.vox.com/

**Comment by paulrouget** [comment]
This has already been fixed. We need a webrender update though.

Closing in favor of https://github.com/servo/servo/issues/11358

**Comment by Gozala** [comment]
Latest servo build fixed servo/servo#11358 but this is still broken

**Comment by Gozala** [comment]
Looks like we have servo/servo#11650 on this one.

**Comment by paulrouget** [comment]
Yeah. Closing in favor of https://github.com/servo/servo/issues/11650.
