### ISSUE TITLE
Cmd-T doesn't work anymore

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1060]

**Comment by Gozala** [comment]
Can you elaborate ? I think what you see (on servo) is that opening a link does not open new tab as expected and then when you hit `CMD-T` it does nothing, but what is really going on is that `New Tab` is already open.

If you try the same in Electron after you open a new tab, `CMD-T` jumps back to `New Tab` page.

**Comment by paulrouget** [comment]
Oh right. So there's no way to open multiple new tabs. That's unexpected.

**Comment by paulrouget** [comment]
anyway - closing issue.

**Comment by Gozala** [comment]
> Oh right. So there's no way to open multiple new tabs. That's unexpected.

Well supposedly with #11539 clicking links on dashboard will open them in new tabs (already a case in Electron). Another issue is that typing in address-bar on new tab page should open whatever you typed in new tab vs navigate away which will be fixed by #1055
