### ISSUE TITLE
Make the newtab page look a bit more simple

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1062]
I know it's probably not the right time to bikeshed, but I don't like the current look. It's too big.

Here are 3 images:
1. current design
2. proposed design
3. proposed design with wallpaper support

Maybe it's better.

![1](https://cloud.githubusercontent.com/assets/373579/15706738/5fea0178-27f5-11e6-9641-ea25b90e4a91.png)
![2](https://cloud.githubusercontent.com/assets/373579/15706739/5febb3ba-27f5-11e6-82b6-0042c2dff34f.png)
![3](https://cloud.githubusercontent.com/assets/373579/15706740/5febe02e-27f5-11e6-8980-a2eecfa699c9.png)

**Comment by Coder206** [comment]
@paulrouget I agree, I like the last the most. The first is much of a copy of Speed Dial. Maybe let's give the freedom to choose to the user.

**Comment by julianrichen** [comment]
If you pick the new design you also avoid needing to create [tiles](https://github.com/browserhtml/browserhtml/tree/master/src/about/newtab/tiles) for the top 100 sites since you are using favicons instead.

**Comment by tschneidereit** [comment]
Let's talk about this in London the week after next.

**Comment by Gozala** [comment]
Unless I'm mistaken we decided to make some tweaks (that already landed) but otherwise leave as is.
