### ISSUE TITLE
Pressing Esc with a single tab open sometimes quits the browser

### ISSUE THREAD

**Issue by tschneidereit** [browserhtml/browserhtml#1063]
STR:
- Open Servo using `servo -w -b --pref dom.mozbrowser.enabled http://localhost:6060`
- Click on the Wikipedia tile
- Wait for the load to finish
- Press `Esc`

This is using rev b55f284e46c6fc720ebc66819dc1d91d83a27587 and today's homebrew servo.

**Comment by paulrouget** [comment]
You're missing some prefs: https://github.com/browserhtml/browserhtml/blob/master/gulpfile.babel.js#L145

**Comment by tschneidereit** [comment]
Hrm, yes. Can't we make that the default? Why would it make sense for `Esc` to ever close the app?

**Comment by paulrouget** [comment]
> Can't we make that the default? Why would it make sense for Esc to ever close the app?

When you're not working on browserhtml I guess? Feel free to file a servo issue.
