### ISSUE TITLE
Sidebar does not hide after tabs are switched with `ctrl tab` keybinding

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1069]
I suspect this is due to `ctrl` keyup not being dispatched. I think it's regression from the latest servo I have installed today.

**Comment by Gozala** [comment]
As I suspected issue is related to `keyup` event not being dispatched when `control` key is released. I have submitted servo/servo#11547 for this.

**Comment by paulrouget** [comment]
Works for me with the new build.
