### ISSUE TITLE
Consider supporting mozprivatebrowsing

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1071]
https://github.com/servo/servo/pull/11544 is about to land.

I don't think it would cost too much to add a button somewhere to create a private tab.

Not sure yet, but worth considering.

Marking this as P1. Not for the implementation, but just to think about how this could be done. If it's not too much work, let's do it.

**Comment by Gozala** [comment]
@paulrouget This requires some UX work & I honestly don't think it's going to make a much difference in terms of demoing or talking to people about browser.html so I'd rather put it off & think about it after All Hands

**Comment by paulrouget** [comment]
I think it's cool to show that servo supports private browsing.

/cc @metajack what do you think? Is it worth adding that in browserhtml?

**Comment by metajack** [comment]
I don't feel strongly. On the one hand it's cool to show off that we can already do it, on the other it is probably not something we want people to think is usable yet, because it might still have bugs.

cc @larsbergstrom

**Comment by Gozala** [comment]
This is clearly not going to happen until we get runtime & embedding API. So closing it for now.
