### ISSUE TITLE
Window does not has rounded corners

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1081]
It seems that servo is failing to clip iframes even within the window boundaries:

<img width="885" alt="screen shot 2016-06-03 at 9 13 17 am" src="https://cloud.githubusercontent.com/assets/21236/15786091/87001d3a-296f-11e6-8f6f-e43614414228.png">

This also seems to be a regression from last servo build as it did not used to be the case given the screenshots I've being posting earlier this week.

**Comment by paulrouget** [comment]
Known issue that has been downgraded to P2: https://github.com/servo/servo/issues/9983
