### ISSUE TITLE
When sidebar is pinned, the close button prevents clicking on the tab

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1086]

**Comment by bheesham** [comment]
Additional acceptance criteria: 

>bhee: the x that moves over should only move over when the full sidebar is showing, not just the anchored version

- cbrewster

**Comment by Gozala** [comment]
If someone want's to work on it I'm happy to mentor.

**Comment by Coder206** [comment]
@Gozala If you don't mind, I'll take it.

**Comment by Coder206** [comment]
@Gozala I would like to help out here.

**Comment by Gozala** [comment]
It looks like this was fixed
