### ISSUE TITLE
Implement better support/error reporting for file:// protocols

### ISSUE THREAD

**Issue by sole** [browserhtml/browserhtml#1088]
Right now we can't access file:// urls

Not sure about the security implications of this, etc. In the meantime we can launch a local server, obviously.

**Comment by sole** [comment]
Correction: it seems like we can access them, but if the loading doesn't work, there's no way to know what the issue was because you only get a white screen

**Comment by tschneidereit** [comment]
I get an error screen when trying to load non-existent `file:` urls: http://i.imgur.com/6CUV55I.png

**Comment by Gozala** [comment]
It's unlikely for us to do anything here until we get a runtime, but we should consider this under the embedding API.
