### ISSUE TITLE
Support loading an initial URL

### ISSUE THREAD

**Issue by jdm** [browserhtml/browserhtml#1089]
This would allow us to support passing an initial URL like ./`mach run -r -b http://mozilla.org`, which I always forget doesn't work.

**Comment by jdm** [comment]
I'm imagining a query string parameter for the initial browser.html page would do the trick.

**Comment by Gozala** [comment]
@jdm we already have machinery in place for query params as they being used to pass in certain configurations. We could add `url=http://mozilla.org` for opening it in a tab.

**Comment by linclark** [comment]
I've been looking for a way to get more familiar with the browserhtml code base and this seemed like a good issue to get started on. I've posted a first pass in #1187. I'm not sure whether this is the correct approach, so please let me know if I should approach it a different way.

**Comment by Gozala** [comment]
> I've been looking for a way to get more familiar with the browserhtml code base and this seemed like a good issue to get started on. I've posted a first pass in #1187. I'm not sure whether this is the correct approach, so please let me know if I should approach it a different way.

Hi @linclark thank for taking time to look into code base and & a pull, I really appreciate. I will provide inline commentary about the changes in the pull request itself.
