### ISSUE TITLE
Leaving pointer from title from the bottom leaves it hovered

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1100]
Steps to reproduce:
1. Hover the page title, it will turn grey
2. Move mouse quickly to the bottom, if you do it quick enough title remains grey. It should turn transparent though regardless how fast you leave the title.

**Comment by paulrouget** [comment]
This is a regression of https://github.com/servo/servo/issues/7865

Filed https://github.com/servo/servo/issues/11864
