### ISSUE TITLE
browser.html breaks on first page load

### ISSUE THREAD

**Issue by jonathandturner** [browserhtml/browserhtml#1106]
I filed a similar issue on the Servo repo (https://github.com/servo/servo/issues/11905).  Basically, browser.html breaks for me during the first page load and the location box is no longer clickable after this happens.  

What I posted to them:

In a recent build (starting in the last week or so), if I run servo with -b (./mach run --release -b) to get browser.html, and I navigate to a page, I get a spew of messages like this in the terminal:

```
ERROR:js::rust: Error at file:///Users/jturner/Source/servo/target/release/build/browserhtml-0964734a748088d9/out/components/main.js:10:3406: e is undefined

ERROR:js::rust: Error at file:///Users/jturner/Source/servo/target/release/build/browserhtml-0964734a748088d9/out/components/main.js:10:3406: e is undefined

ERROR:js::rust: Error at file:///Users/jturner/Source/servo/target/release/build/browserhtml-0964734a748088d9/out/components/main.js:10:3406: e is undefined

ERROR:js::rust: Error at file:///Users/jturner/Source/servo/target/release/build/browserhtml-0964734a748088d9/out/components/main.js:10:3406: e is undefined
```

This can go for pages for only a few dozen times depending on the page I load.  After this happens, the loading indicator appears to freeze and I can no longer click on the location box for browser.html.  I've tried facebook.com, google.com, youtube.com, and yahoo.com and they all give me the same result.

I'm on OS X 10.11.5.

**Comment by huwdp** [comment]
I can confirm I also have the same issue as yourself.

**Comment by ConnorGBrewster** [comment]
I believe this is not an issue on master bhtml, so this could possibly be fixed already.

**Comment by paulrouget** [comment]
Not happening in master. I'll updated bhtml in Servo.

**Comment by paulrouget** [comment]
https://github.com/servo/servo/pull/11922
