### ISSUE TITLE
Bring the speed dial to Windows

### ISSUE THREAD

**Issue by Coder206** [browserhtml/browserhtml#1116]
The speed dial is missing when using Windows 10

**Comment by ConnorGBrewster** [comment]
@Coder206 are you working off of latest servo/master?

**Comment by Coder206** [comment]
@ConnorGBrewster Yes, I am pretty sure.

**Comment by Coder206** [comment]
@ConnorGBrewster Hold on...

**Comment by Coder206** [comment]
@ConnorGBrewster I just pulled the code from upstream master, I was missing a few files. So the answer to your question: no.

**Comment by paulrouget** [comment]
> I just pulled the code from upstream master

Servo master or bhtml master?

**Comment by paulrouget** [comment]
Well, both should have the speed dial since the 0.1.8 update.

@ConnorGBrewster do you see the speeddial now?

**Comment by Coder206** [comment]
@paulrouget Servo master.

**Comment by tschneidereit** [comment]
@Coder206 what did you mean by "I was missing a few files" above? And do things work for you now?

**Comment by Coder206** [comment]
@tschneidereit I meant there were file changes. I am not sure, just recompiling now.

**Comment by Coder206** [comment]
I was missing some code!
