### ISSUE TITLE
Error running browser.html on windows: ./python/servo/post_build_commands.py line 161

### ISSUE THREAD

**Issue by samal84** [browserhtml/browserhtml#1126]
Tried building browser.html on Windows 7 and got this error on running ./mach run -r --browserhtml:
/home/rasmuss/source/servo/target/release/build
```
Error running mach:

    ['run', '-r', '--browserhtml']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command. Consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 84] Accessing a corrupted shared library

  File "./python/servo/post_build_commands.py", line 161, in run
    raise e
```

Full console output attached.
[console-output.txt](https://github.com/browserhtml/browserhtml/files/341642/console-output.txt)

**Comment by tschneidereit** [comment]
@samal84 does this only happen if you pass `--browserhtml`, or also if you just do `./mach run -r`?

**Comment by samal84** [comment]
`./mach run -r` gives exactly the same thing.

**Comment by tschneidereit** [comment]
Ok, then it's definitely not a browser.html issue. Can you open an issue on [servo/servo](/servo/servo)?

**Comment by tschneidereit** [comment]
@samal84, but thanks for reporting. I know it's not always obvious which project to report things for.

**Comment by samal84** [comment]
Thank you @tschneidereit 

Created here: https://github.com/servo/servo/issues/12051
