### ISSUE TITLE
Dismiss the sidebar when clicking on a tab

### ISSUE THREAD

**Issue by tschneidereit** [browserhtml/browserhtml#1128]
using `ctrl+tab` to go through the list of tabs shouldn't close the sidebar if it's currently open. Clicking on a tab should, though: it shouldn't take two clicks to select a tab.

This'd be really nice to get for the tech demo.

**Comment by Gozala** [comment]
So according to UX design behavior should be following:

Once tab selection is complete it should hide the sidebar. This includes selection via `ctrl + tab` and also `click` on the tab. Currently `ctrl+tab` works as expected, it will hide sidebar whenever you release `ctrl` key so you can move selection without hiding sidebar, but once you're done it'll hide.

Thing that does not work as expected right now is the fact that selecting tab with click does not hide sidebar as it supposed to. I'll submit a patch to fix that.
