### ISSUE TITLE
Show target URL on mouse hover

### ISSUE THREAD

**Issue by glennw** [browserhtml/browserhtml#1144]
Firefox pops up a status bar showing the URL under the mouse, so you can see it before you click a link.

browser.html should do something similar - perhaps with a different UI - but allowing the user to see a URL before clicking.

**Comment by Gozala** [comment]
We talked about using titlebar for this in past, I don't think we have concrete mockups though.

**Comment by paulrouget** [comment]
> We talked about using titlebar for this in past

It'd be ok with this, as long as we keep it mind that this could be used by a website to spook its url.

Maybe this could look like this:

```
 [                       page title                      ]
… over link …
[             page title → next.com            ]
```

**Comment by paulrouget** [comment]
For reference: http://electron.atom.io/docs/api/web-contents/#event-update-target-url

**Comment by Gozala** [comment]
We should consider hover events for embedding API, but for now nothing is going to happen, so closing.
