### ISSUE TITLE
Navigation buttons on mouse are ignored

### ISSUE THREAD

**Issue by moosingin3space** [browserhtml/browserhtml#1154]
I have a mouse with buttons on each side that are used for moving Forward and Back. The buttons work in Firefox 47.0 and Chrome 50.0.2661.102, but not with the Servo/browserhtml nightly build from today. Alt-Arrow works for navigation, but the mouse does not. This was observed on Ubuntu 14.04.4.

**Comment by paulrouget** [comment]
I'm wondering how the key event looks like in glutin. Not sure it's supported.

**Comment by Gozala** [comment]
Wo are not listening to any key events other than `Cmd/Control + ArrowLeft/ArrowRight` which is why it does not work. If someone want's to investigate what events are supposed to dispatch on such keys (by looking at firefox source) and then hooking them up, I'm happy to mentor.

**Comment by moosingin3space** [comment]
Unfortunately, I no longer have access to the mouse in question, but it did work in Firefox. Is this a bug in browser.html or in Servo?

**Comment by Gozala** [comment]
We definitely don't hook into anything other than what I mentioned earlier so it's definitely a bug in browser.html. That being said there also could be a bug in servo but it's difficult to say. Someone with such mouse needs to investigate

Typed on tiny keyboard

**Comment by paulrouget** [comment]
There are native goback goforward key events. We need to support them. Later though.

**Comment by Gozala** [comment]
Closing this as there no immediate plans to tackle this. If someone wants to fix that let me know & I'd be happy to help & reopen this.
