### ISSUE TITLE
Typing too fast on the url bar mess things up

### ISSUE THREAD

**Issue by bltavares** [browserhtml/browserhtml#1155]
I was trying to access a website that I type fast, but I think that when the suggestion response arrives delayed, it mess the cursor up.

How to reproduce: Try to access a website by typing it really fast.
What happens: The cursor jumps around, and the typed url is wrong.

Here is a recording of the problem: https://gfycat.com/FaintFewDipper

**Comment by ConnorGBrewster** [comment]
filed on Servo in servo/servo#12039

**Comment by Gozala** [comment]
This is duplicate of #1157, please subscribe there for updates on this.
