### ISSUE TITLE
Suggestions sometimes blow away what you typed

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1157]
@fitzgen keeps running into issue where what he types gets blown away by the suggestions. Typically typing `git` seems to reproduce it every now and then.

**Comment by Gozala** [comment]
@fitzgen if you can reproduce the issue with this pull request. You'll be able to do a session record (see [instruction](https://github.com/browserhtml/browserhtml/wiki/Browser-options#record)):
https://github.com/browserhtml/browserhtml/pull/1015

Then I'll be able to reproduce & figure out what's going on.

**Comment by fitzgen** [comment]
This eventually got typing "git" turning into a "GTE" completion: https://api.github.com/gists/c3614266cfca6cd0ba9efa65a0a8a794

**Comment by Gozala** [comment]
Actual url we care about is:

https://gist.githubusercontent.com/anonymous/c3614266cfca6cd0ba9efa65a0a8a794/raw/6202b71e77a810ef29e837b8de7c10fc291767bd/snapshot.json
