### ISSUE TITLE
Large images are not rendered, sometimes

### ISSUE THREAD

**Issue by yump** [browserhtml/browserhtml#1158]
1. Go to [this picture of an owl on the Wikimedia commons](https://commons.wikimedia.org/wiki/File:Tyto_alba_-British_Wildlife_Centre,_Surrey,_England-8a_(1).jpg).

2. Try opening the "other resolutions".

On my machine, the 1504x1880 image never renders (blank white page), and the 819x1024 image sometimes doesn't render.

OS: Fedora 23, Ubuntu libssl loaded with LD_LIBRARY_PATH.

Graphics: GTX 660 with Nvidia blob 367.27

**Comment by Gozala** [comment]
@yump thanks for the report. Please submit UI related issues here, and rendering issues into https://github.com/servo/servo/issues instead.

Moved this to https://github.com/servo/servo/issues/12281
