### ISSUE TITLE
All and sundry problems with the URL bar

### ISSUE THREAD

**Issue by yump** [browserhtml/browserhtml#1159]
First, the end of the URL is cut off even when there is plenty of horizontal space to display it.

Second, the URL cannot be copied. No right click menu.  Ctrl+C doesn't work.  URL appears highlighted, but cannot be middle-click-pasted into other applications.

Third, the URL cannot be edited.

OS: Fedora 23, Ubuntu libssl loaded with LD_LIBRARY_PATH.

Graphics: GTX 660 with Nvidia blob 367.27

**Comment by Gozala** [comment]
> First, the end of the URL is cut off even when there is plenty of horizontal space to display it.

Could you please provide a screenshot or something, to illustrate what you mean ? Input field intentionally has fixed horizontal size, which does not take full horizontal space. But I guess you might see something else.

> Second, the URL cannot be copied. No right click menu. Ctrl+C doesn't work. URL appears highlighted, but cannot be middle-click-pasted into other applications.

For now servo has not implement mouse interactions with input fields see servo/servor#10083. We also have no context-menus implementations neither on servo nor browser.html. As of `Ctrl+C` it should work, if it does not please submit bug into https://github.com/servo/servo/issues instead. Please note that mouse interaction with input field sometimes put input into invalid state and `Ctrl+C` may not work afterwards. I expect that to be fixed once above mentioned issues is.
