### ISSUE TITLE
Bug Reports via GET too long for NGINX, 414, should probably be a POST

### ISSUE THREAD

**Issue by Min1123** [browserhtml/browserhtml#1165]
Attempting to play a video on YouTube caused an error, a report button was displayed with a stacktrace in the app, but when I clicked on it, it tried to submit the bug, but the URI was too long on the GET to NGINX, so NGINX rejected it with a 414 code.

This should probably be marshaled to something and sent to a POST endpoint instead.

**Comment by Gozala** [comment]
Problem is we can't actually use POST as we're using default browser to submit issues, so there's no way could tell it to send POST requests. That being said it's good to know that we are hitting the URL limits, we'll try to come up with an alternative way to report issues.

Would you mind posting a URL that hits the limit next time you're run into this ?

P.S.: youtube isn't going to work as servo does not yet has HTML video / audio nor flash support.

**Comment by Gozala** [comment]
I wonder if we could embed gists in here:

<script src="https://gist.github.com/Gozala/457967c3f6908e00b99b4379335c254c.js"></script>
