### ISSUE TITLE
Auto complete should not provide selected completions on deletes

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1167]
Currently if you type something, very likely you'll get an autocomplete with completion being selected. Idea is that you can continue typing, if competition isn't what you care about, or hit enter to navigate to suggestion.

Unfortunately if you had a typo and need to delete several characters, you'll end up needing to double backspace per character.

1. To delete selection.
2. To delete actual character.

This is not ideal. We could probably do what Safari does here. Which is do not provide selected completion if backspace was typed, only provide it if additional characters were typed.

**Comment by suhr** [comment]
> or hit enter to navigate to suggestion

Sometimes you just don't want the suggested part at all.

**Comment by Gozala** [comment]
> Sometimes you just don't want the suggested part at all.

True. Our assumption is that top suggestion more often will be where you want to go than not. Which is why we decided on current default.
