### ISSUE TITLE
All caps and shift enabled for keys

### ISSUE THREAD

**Issue by Coder206** [browserhtml/browserhtml#1177]
When I tried a build of Servo and bhtml after pulling the master branch yesterday at around 8:30, the characters in bhtml's address bar were capitalized and it was like shift was being pressed continually. (When writing commands in MinGW, the characters were lowercased).

This issue was found on a Windows 10 system.

**Comment by paulrouget** [comment]
Seen that somewhere else in Servo issues.

Can you reproduce without browserhtml?

**Comment by Coder206** [comment]
@paulrouget Not really sure what to make of it, unable to reproduce today in Windows 10...
