### ISSUE TITLE
Electron app doesn't work without Node integration

### ISSUE THREAD

**Issue by freebroccolo** [browserhtml/browserhtml#1179]
I am trying to load the electron app with electron `v1.2.6`. The window shows up with the address bar and you can type stuff in but it won't actually load any URLs or anything unless `nodeIntegration` is re-enabled [here](https://github.com/browserhtml/browserhtml/blob/master/main.js#L56).

Is this expected? Is there some other way to start the app with electron that doesn't have this issue?

**Comment by Gozala** [comment]
Hi @freebroccolo thanks for letting us know. I have being testing it with electron v1.0.1 without `nodeIntegartion` & it works fine.

I guess something has changed in newer versions of Electron. I'll try to investigate into this, when I get a chance. That being said, Electron support isn't very high priority so I may not get to this soon.

If you'd be willing to look into what's breaking I'd be happy to help figuring / fixing things up to make so it works with latest version without needing to enable `nodeIntegration`.

**Comment by Gozala** [comment]
It seems that in 1.11.1 `webview` tag is disabled when `nodeIntegration` is off in host window, which would explain this issue: https://github.com/electron/electron/releases/tag/v1.1.1

**Comment by freebroccolo** [comment]
Ah, thanks for looking into this. I suspected it was something like that. Do you have a workaround in mind? What about leaving `nodeIntegration` enabled but running a preload script to remove unsafe modules?

**Comment by Gozala** [comment]
> Ah, thanks for looking into this. I suspected it was something like that. Do you have a workaround in mind? What about leaving nodeIntegration enabled but running a preload script to remove unsafe modules?

That could be an intermediate solution (I'd be happy to take a pull request for this 😉).

In longer term I would like to find out why Electron disabled `webview` tag (my guess after skimming through the linked issues in release notes, is in order to re-enable sandboxing) or what is expected usage. For example how does brave browser go about it ?

**Comment by freebroccolo** [comment]
> In longer term I would like to find out why Electron disabled webview tag (my guess after skimming through the linked issues in release notes, is in order to re-enable sandboxing) or what is expected usage. For example how does brave browser go about it ?

@Gozala I'm not sure how they do it in the brave browser but from [this issue](https://github.com/electron/electron/issues/6157) it sounds like preload may be the expected approach.

**Comment by poiru** [comment]
[Issue #5173](https://github.com/electron/electron/issues/5173) has some context. Enabling `nodeIntegration` is not safe because of that bypass.

**Comment by paulrouget** [comment]
> In longer term I would like to find out why Electron disabled webview tag (my guess after skimming through the linked issues in release notes, is in order to re-enable sandboxing)

There are 2 kind of privileges: privilege to use `<webview>`, privilege to use node. Both have higher privileges than normal content. It's hard to expose `<webview>` in a way that it works with normal content privilege in a secured way. Webviews grows significantly the attack surface of the engine. For example, recently, there were 2 security issues recently reported where a webview could enable nodeIntegration. It's just a lot easier to make these two privileges only one, to avoid people assuming they are safe enabling only one privilege.

And I think this decision makes sense.

> how does brave browser go about it ?

Brave does nothing about it. They use nodeIntegration + webview. As for the sandboxing, the sandboxed renderer process run without nodeIntegration anyway.

I think this ultimately makes sense, and we do something more or less similar in Servo where special privilege mean: mozbrowser + app-level rights (like system XHR). We are even more strict as we don't allow such privilege to be granted in iframes/webviews.
