### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by vtomole** [browserhtml/browserhtml#1186]
I tried npm install --no-optional and I got this:http://pastebin.com/GCyMKccW

**Comment by Gozala** [comment]
@vtomole It seems that npm is failing to install `flow-bin@0.28.0` can you try running `npm install flow-bin@0.28.0` and if that still fails reporting an issue to https://github.com/facebook/flow

P.S.: It seems to install just fine on my machine & travis as well.

**Comment by Gozala** [comment]
Closing as I have not heard anything back.
