### ISSUE TITLE
mk_add_options: command not found

### ISSUE THREAD

**Issue by vtomole** [browserhtml/browserhtml#1190]
I'm trying to build gecko by following these instructions:https://github.com/browserhtml/browserhtml/wiki/Building-Graphene-%28Gecko-flavor%29

when I run:mk_add_options AUTOCLOBBER=1, I get mk_add_options: command not found.

**Comment by paulrouget** [comment]
autotools are probably not installed. See https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build

This is unrelated to bhtml. Closing.
