### ISSUE TITLE
Paste from clipboard not working

### ISSUE THREAD

**Issue by samuknet** [browserhtml/browserhtml#1191]
I have noticed when trying to paste (using Cmd-V) anywhere in Servo while using browser html, nothing happens on my machine.  

Most commonly occurs when trying to paste a URL into the URL bar although the issue also occurs trying to paste in any text input within a web page.

I am running on OS X, El Capitan if this is of any help! 😃

**Comment by paulrouget** [comment]
Because of this: https://github.com/servo/servo/pull/12507

**Comment by yisibl** [comment]
Do you have any other plans to support it?

**Comment by Gozala** [comment]
This will get fixed once linked servo issues is fixed.
