### ISSUE TITLE
Consider switching to google.com

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1217]
We all love duckduckgo, but I think we should rather use Google to make sure it's properly tested.

Does it make sense?

**Comment by tschneidereit** [comment]
I'm not convinced. At this point it doesn't seem like google working should have much priority over other sites. Once we get closer to any sort of production usage, that changes, obviously. At that point, we should have robust regression testing for popular sites, though.

**Comment by paulrouget** [comment]
Google is the most used website in the world. I think that's a good reason to make it a priority :)

Servo got better at rendering duckduckgo because it's what we use today. Now it works, maybe it's time to improve google.com.

Also - the google result page appears to work pretty well. So it won't break browserhtml I think.

**Comment by tschneidereit** [comment]
> Google is the most used website in the world. I think that's a good reason to make it a priority :)

I agree, obviously. I'm less sure about whether we need to make it a priority *now*, though.

**Comment by paulrouget** [comment]
The benefit is that we'll get people to test google.com.
If it doesn't cost us to much trouble, it's worth it.

**Comment by Coder206** [comment]
@paulrouget I think it would be more worth while to put efforts into allowing different default search engines so that people can use the one they feel comfortable with initially - instead of having to search for it with another search engine or type it out.

**Comment by Gozala** [comment]
We decided to do nothing for now
