### ISSUE TITLE
Implement sidebar animation as a CSS transition.

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1221]

**Comment by paulrouget** [comment]
I believe this is better because for performance, but can you explain why we want to do that now?

**Comment by Coder206** [comment]
I would like to help implement this.

**Comment by Gozala** [comment]
@Coder206 Thanks! But I would suggest to hold on with it for now. I'm having second thoughts on this as we were planning to add swipe based interaction to the sidebar, so you could slide it in / out to reveal / hide tabs. But if rewrite sidebar animation in CSS it would only make it more complicated :(

I am so sorry for constantly telling you please don't. How about we'll triage issues and identify ones that are good to get started with. I'll tag them with [Help needed](https://github.com/browserhtml/browserhtml/labels/Help%20needed)

**Comment by Coder206** [comment]
@Gozala It's fine! I understand the circumstances.
