### ISSUE TITLE
TypeError: Couldn't open URL: Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1230]
browser.html fails to submit crash report, due to exception at: [`./src/browser/IssueReporter.js:103`](
https://github.com/browserhtml/browserhtml/blob/31ae5cb94b02a951994895e9aca4bdae357bb16f/src/browser/IssueReporter.js#L103) with following message:

```
TypeError: Couldn't open URL: Operation not permitted (os error 1)
```

You can reproduce it with latest nightly: `Servo 0.0.1-4cefbcc` and following steps:

1. click on hacker news on newtab page
2. close the tab 
3. click on github on newtab

**Comment by Gozala** [comment]
@paulrouget can you look at it ? Please note that currently we don't log error so in order to see it you'd need to manually modify mentioned line to log it or do whatever you want.

**Comment by paulrouget** [comment]
I'll look.

**Comment by paulrouget** [comment]
Not surprising.

We enabled sandboxing. https://github.com/servo/servo/issues/12869

**Comment by paulrouget** [comment]
I'm about to disable multiprocess and sandboxing to address 3 recent regressions. See https://github.com/servo/servo/issues/12868
