### ISSUE TITLE
Swipe gestures

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1247]
In order to implement / revive  #842  we need to be able to receive swipe gestures from servo. Or maybe an overscroll events that @paulrouget brought up in the past. wheel events may be another option if we can figure out somehow when there's nothing to scroll in the page itself.

I believe on servo side this would be servo/servo#6226 for swipe gestures. And something to be able to receive events on the root document, cause currently all events are captured by iframe content and never bubble up to browser.html document so we can't really do much.

@paulrouget could you please submitting servo issue for the iframe event bubbling as I think you know better what intermediate solution might before we get new browsing API.

**Comment by Gozala** [comment]
Also I remember @gordonbrander talking suggesting to just implement [Pointer Events](https://www.w3.org/TR/pointerevents/#pointerevent-interface) for touchpads which would essentially give us swipe gestures (on any number of fingers) without designing our proprietary swipe gesture API.

**Comment by paulrouget** [comment]
To achieve #842, we will need gesture events support in the compositor, and we should use CompositorWorkers to move the viewport elements.

I'm working on a draft describing this.

**Comment by paulrouget** [comment]
See my comment here: https://github.com/servo/servo/issues/6226#issuecomment-246967723
