### ISSUE TITLE
API for extracting data from the navigated site

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1248]
If we want to explore [The Future of Browser History](https://medium.freecodecamp.com/browserhistory-2abad38022b1#.pf64nbb63) we need a way to extract certain contents from the visited sites. In gecko we hacked together #332 in Servo we have nothing so far.

We would be great if solution will be compatible with work done on context graph side, which I believe would be:

https://github.com/mozilla/fathom
https://github.com/mozilla/heatmap

**Comment by paulrouget** [comment]
So beside being able to execute content script, what else is needed?

**Comment by Gozala** [comment]
> So beside being able to execute content script, what else is needed?

Communicate back with a browser.html I have not looked into context-graph code yet to be able to tell exactly what they depend on.

Another thing that would really help would be a pixel data, maybe it could be included on first paint ? Or have an API to manually request it. So we could paint titlebar in the same color. From what I can tell metadata based approach rarely gives us desired rusts.

**Comment by Gozala** [comment]
To be more clear I think doing whatever we had in Gecko as short term solution before we get browsing API 2.0 would be a good enough intermediate solution.

**Comment by paulrouget** [comment]
Understood.

**Comment by paulrouget** [comment]
Let's use this issue for `executeScript`. For pixel data: https://github.com/browserhtml/browserhtml/issues/1249

**Comment by paulrouget** [comment]
See https://github.com/servo/servo/issues/13263
