### ISSUE TITLE
Specification for providing information about hovered link

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1256]
Spec for https://youtu.be/sKCTzRDAvuw

**Comment by patrykadas** [comment]
I think that we have to handle both at the same time: hovering a link and clicking it. 

In terms of transition: I believe that the current problem is that pages are swaping, instead of switching - If it wasn’t for learnt behavior I would be unable to figure out that swipe back means going to the previous page, as they are both in the same place, there is no physical movement nor any other indicator. It’s more like current page is morphing to the new one.

It would be nice to simply show it:

Opening new link:
https://www.youtube.com/watch?v=ySMzOv65m30

New link target blank:
https://www.youtube.com/watch?v=p_sAu7QBlDI

**Comment by Gozala** [comment]
> I think that we have to handle both at the same time: hovering a link and clicking it.
> 

I agree in terms of designing a feature, implementation wise it may make sense to do them in two steps though.

> In terms of transition: I believe that the current problem is that pages are swaping, instead of switching - If it wasn’t for learnt behavior I would be unable to figure out that swipe back means going to the previous page, as they are both in the same place, there is no physical movement nor any other indicator. It’s more like current page is morphing to the new one.

I agree actually we had few ideas in this regard:

https://drive.google.com/file/d/0B1az_KF0ZYc_NThWREg5SDB3aE0/view?usp=sharing
https://drive.google.com/file/d/0B1az_KF0ZYc_WlFxUmhhMFJZQmc/view?usp=sharing
https://drive.google.com/file/d/0B1az_KF0ZYc_eXh1R20wVjNnX1U/view?usp=sharing
https://drive.google.com/file/d/0B1az_KF0ZYc_dnlsU2Etd3UxcGc/view?usp=sharing

> 
> It would be nice to simply show it:
> 
> Opening new link:
> https://www.youtube.com/watch?v=ySMzOv65m30
> 

I am not big fan of the rendering (backward progressbar, shared titlebar) sorry.

What if we did something along this lines instead:
https://drive.google.com/file/d/0B1az_KF0ZYc_dnlsU2Etd3UxcGc/view?usp=sharing
But with a following twist:

When you hover a link we slide over from the bottom just a titlebar of the page you're hovering with a security info color coded as in your example. In fact if link is safe we could start a preload, otherwise we do it if you click a link. While page is loading we could also display process with a regular progressbar that we have have attached to the bottom of it's titlebar. Once first render happen new page will slide over the current page as shown in video (assuming link was actually pressed).

Only thing to work out would be how do you indicate that your are hovering and page is just preloading vs you actually clicked the link. Maybe we could display part of titlebar without progressbar on hover and revealed progressbar when you click if it's not loaded yet and just slide it over if it's already preloaded.

In fact I think it would be amazing if we could preload all the links before you'd hover them, that way we could display actual page titlebar and just slide it over on click without any progress bar or delay.

I think it would fit better with rest of the interactions if instead of sliding over from the bottom we did slide current page down a bit to do the same thing from top. That is because we would be able to display the whole thing naturally in the "overview" mode as not loaded page will be hidden behind current page, if we do it from the bottom then in overview mode you'd expect to see the whole note yet loaded page below the current one which would ugly due to blank page and it also may integer with tabs below it.

> 
> New link target blank:
> https://www.youtube.com/watch?v=p_sAu7QBlDI

I don't get this what I is supposedly happening here ?

**Comment by Gozala** [comment]
> New link target blank:
>> https://www.youtube.com/watch?v=p_sAu7QBlDI
>> I don't get this what I is supposedly happening here ?

Oh I get it now. It opened link in the background tab! To be honest I just guessed it from the description visual feedback was really unclear to me.

**Comment by patrykadas** [comment]
Thank you for the feedback! 

In terms of loading a page, I think we should treat the transition horizontally, as afterwards you are sliding left / right to access previous page, not scrolling top / bottom. I would love to show user a movement in the history and at the same time indicate what can be done (slide to access previous page). 

I agree with everything else and I am preparing prototypes.

**Comment by Gozala** [comment]
I think so too! Maybe once load is new page can squeeze in from top / bottom pushing current page to the left slide which could give it a more natural horizontal feel ?

Typed on tiny touchscreen

**Comment by Gozala** [comment]
@patrykadas I have being thinking about this more and I think that showing titlebar for hovered / clicked link behind the current tab at the top of it has really nice properties:

- If you click a link once it's loaded we can slide current page to the left squeezing new page into the center of the view. This makes it somewhat intuitive that previous page is on the left so if you keep scrolling you could reach it.
- If you click a link with `target="_blank"` or with cmd / ctrl button pressed we could display titlebar again at the top and even show you load progress. Once it's done we could do slightly different squeeze in animation where current page moves further down and new page further up and then current page pushes it further up. Providing visual feedback that it opened a new tab above it.
- If you do not care about load indicator all you have to do is scroll a bit to push the preloading page under current one out of the view.


What do you think ?

**Comment by patrykadas** [comment]
> If you click a link once it's loaded we can slide current page to the left squeezing new page into the center of the view. This makes it somewhat intuitive that previous page is on the left so if you keep scrolling you could reach it.

I agree, I've tried to do it here:
https://youtu.be/ySMzOv65m30?t=7s

>If you click a link with target="_blank" or with cmd / ctrl button pressed we could display titlebar again at the top and even show you load progress. Once it's done we could do slightly different squeeze in animation where current page moves further down and new page further up and then current page pushes it further up. Providing visual feedback that it opened a new tab above it.

Should a new tab be above current page, or is it to the right? IMO it's a part of the future and I would rather access it by swiping

> If you do not care about load indicator all you have to do is scroll a bit to push the preloading page under current one out of the view.

Not sure about this one, dunno if it needs user's action - I will try to prototype that to get better understanding. Perhaps, as we already know what page is being loaded, just the tiny progress bar above would do.

**Comment by patrykadas** [comment]
Based on your comment this is how I understand our grid. This fits really well with everything else we'd discussed.

![grid](https://cloud.githubusercontent.com/assets/6234032/19475967/f7f9f442-9536-11e6-814f-e1265cf122a3.jpg)

**Comment by patrykadas** [comment]
I was playing around with different effects and directions. 


## Failed attempts 
https://www.youtube.com/watch?v=aHTD-u7YD04
^ Hover link, my only objection would be that it may take too much space to display whole bar. 
It’s grey at first, then it transforms to particular color (red/orange/green). However, there is a mistake in the video - once we got the information about the security of the link, it should stop transforming, but just display red/orange/green, as we already got this data.

https://www.youtube.com/watch?v=o0WDAbzSKTA
As I did not want it to make so much space just on hover, I've made this one, but also was not satisfied, as it is too long.

https://www.youtube.com/watch?v=Cg9XbpUvlDM
It was also taking too long and the transition was not clear, so I kept experiment with curves of animation.


## Satisfying attempts 

https://www.youtube.com/watch?v=gggGfOjwUWA
I am pretty much satisfied with this one, loading bar's color is the color of either favicon or first color on the website (yet to be determined, I think it should be favicon's as most of websites are white nowadays). 

https://www.youtube.com/watch?v=M3Exx04elWg
That's a target blank - page is popping, and after the animation ends we change color of the hamburger icon to mark that there's something below.

Another variation, current page is not moved:
https://www.youtube.com/watch?v=AHQZ8xwOvHI

**Comment by Gozala** [comment]
@patrykadas Are you decided on displaying info at the bottom VS at the top or you just have not got to try that direction yet ?

I think I like `target=_blank` animation especially one where current page does not move, that being said I'm not sure that message there is really intuitive though would be interested how others would react to this. I also remember a lot of thought and justification was put into adding new tabs to the top of the stack vs bottom so if do change that I would like that decision to be at least as argumented.

I also can't help but think that information displayed on hover is way too subtle. It could be a good thing but would be nice to be able to compare. I think even first attempts taking full horizontal space were too subtle, it did not felt like another page overlaying current, I think rounded corners and some shadows under it could make it more visible and provide a clearer message. Also I'd be curious to see an example where titlebar actually changes color for example like it does on http://daringfireball.net it could be too much, but still worth a try IMO.

**Comment by Gozala** [comment]
Also we really need to work out what do we do when you hit escape while clicked link is loading.

**Comment by patrykadas** [comment]
>Are you decided on displaying info at the bottom VS at the top or you just have not got to try that direction yet ?

I am not, however my main argument would be that users usually switch pages, once they completed reading current one, which means they are, in most cases, at the bottom of the current page. It would work in exactly the same way as, let's say - related content.

>I also can't help but think that information displayed on hover is way too subtle.

I was just really worried about occupying too much space, if there are many links and perhaps I just want to 'scan' them fast, constantly blinking big area would be really distracting. Actually, I would really like it to be subtle - even when I'm browsing the web I only sometimes want to check the URL before clicking a link, in most cases I just click, without even looking at the left bottom corner. Current URL on hover in Safari/Opera/Chrome is so subtle it's not making my eyes jump to the bottom-left, which is good and I was trying to do the same - we don't want to distract users. However at the same time I don't have any data on this and it's just my hunch.

**Comment by patrykadas** [comment]
Normal link:
https://www.youtube.com/watch?v=LWngrrw8bU8

Target blank or control/cmd:
https://www.youtube.com/watch?v=ty-gOddE5EQ

**Comment by Gozala** [comment]
> Normal link:
> https://www.youtube.com/watch?v=LWngrrw8bU8

I think like the animation, but I also think it requires a polishing. Here are some of the questions it raises:

1. Spatial model is confusing, so titlebar is overlayed with a new titlebar and once page is loaded somehow old titlebar is uncovered from the back as page is detached.  I guess that is possible if three were thee layers in following stacking 1. Next Page. 2. Current Page. 3. Current Page Header. 4. Next Page Header. Maybe ppl don't think about but if they do it's going to be weird.

**Comment by julianrichen** [comment]
What happens if a user wants to opens multiple tabs in the background very quickly? The current animations stops users from CTRL + Clicking many links at once and pulls them away from the content and forces them to wait ~0.8s for the animation to finish.

I would personally suggest an animation that does not zoom or move the content on the current page.

**Comment by patrykadas** [comment]
@Gozala 

In terms of header - I imagined it differently. 
![header](https://cloud.githubusercontent.com/assets/6234032/19732377/e1e7f1de-9ba0-11e6-81b0-707f8e896ddf.png)

Page - oriented elements (URL mostly) are dynamic, however all the elements that are browser's (menu trigger, system controllers, new page) are always fixed and never move. 

This way we can even show the movements during the hover:

Hover without animations:
https://www.youtube.com/watch?v=QPrWKaj9lTo

Hover with animations:
https://www.youtube.com/watch?v=U1OX-w2_xlk

Animations perhaps provide additional feedback from the user, dunno if needed; honestly I think colors should be enough.

>What happens if I scroll while page next page is loading ?

IMO It should be scrollable and loading should happen "in the background".

>What happens if I hover another link while page is loading ?

Nothing, it should be disabled.

>What do you see if we toggle sidebar ?

When exactly? After the page load?

@julianrichen Good point! I was trying to figure out the proper way that's scalable and can work always; I came to conclusion that from the user's point of view loading page in the background is not really *that* important, so I've decided to completely hid it and came to this version:
https://www.youtube.com/watch?v=fydGtiUYE_A

I think it could be improved from visual point of view, however it's just showing functionality.

**Comment by Gozala** [comment]
> @Gozala 

> In terms of header - I imagined it differently. 
> ![header](https://cloud.githubusercontent.com/assets/6234032/19732377/e1e7f1de-9ba0-11e6-81b0-707f8e896ddf.png)

Well the whole header color changes to match the page if page provides necessary metadata & in a future we would like to extract just page colors to do that even without metadata. So system controls are indeed fixed they just overlay everything.

![header-color](https://cloud.githubusercontent.com/assets/21236/19747822/d7a10660-9b92-11e6-9cdf-f9f2af274931.gif)


> Page - oriented elements (URL mostly) are dynamic, however all the elements that are browser's (menu trigger, system controllers, new page) are always fixed and never move.

overview button and new page button aren't actually fixed as you can see if you enter overview they move with a tab.

![overview-mode](https://cloud.githubusercontent.com/assets/21236/19747937/8d66654e-9b93-11e6-9618-c625aef0d2ee.gif)

They could possibly made fixed and fade out instead although that would complicate certain things but doable.

> This way we can even show the movements during the hover:
> Hover without animations:
> https://www.youtube.com/watch?v=QPrWKaj9lTo

> Hover with animations:
> https://www.youtube.com/watch?v=U1OX-w2_xlk

So main difference is that dynamic page part has a full width vs fragment, so I think all that should be still possible.

> Animations perhaps provide additional feedback for the user, dunno if needed; honestly I think colors should be enough.

I think they are too distracting! It maybe be a good thing for insecure links for others I think it's too much. Still though message is confusing current title slides out while page remains and new title slides in. I get what you're trying to communicate and I can be convinced but I still would like to see what I described for comparison.

> > What happens if I scroll while page next page is loading ?
> IMO It should be scrollable and loading should happen "in the background".

I mean what happens visually to the next page's header and progressbar assuming current page's header and sidebar are shown after / during scroll.

> > What happens if I hover another link while page is loading ?
> Nothing, it should be disabled.

But then it would appear non responsive, not to mention that currently you can still change mind and load different link while current page is still visible.

> What do you see if we toggle sidebar ?
When exactly? After the page load?

During page load. Note that currently you'll see following

![overview-while-loading](https://cloud.githubusercontent.com/assets/21236/19748324/bbd0daca-9b95-11e6-9dac-bb3d655c04d2.gif)

**Comment by Gozala** [comment]
> What happens if a user wants to opens multiple tabs in the background very quickly? The current animations stops users from CTRL + Clicking many links at once and pulls them away from the content and forces them to wait ~0.8s for the animation to finish.

> I would personally suggest an animation that does not zoom, move or overlay new content over the content on the current page.

I agree distracting a user would be really bad. Which is also why I was not very fond of scaling.

> This one seemed to be the "best" for that:
https://www.youtube.com/watch?v=AHQZ8xwOvHI

I agree. I still think that is still doable from the top side if we compensate number of pixels taken with a scroll in the current page, but then it still maybe distracting if you focus on the top part of the page, on the other hand same is true for linked demo if you're focused on the bottom part of the page.

> @julianrichen Good point! I was trying to figure out the proper way that's scalable and can work always; I came to conclusion that from the user's point of view loading page in the background is not really that important, so I've decided to completely hid it and came to this version:
https://www.youtube.com/watch?v=fydGtiUYE_A

I frequentely load tab in the background and then keep switching back and forth if it's not loaded yet, so load indicator that would let me know it's ready would be invaluable to me, which may not representative of majority of users of course.

**Comment by patrykadas** [comment]
https://www.youtube.com/watch?v=NUNQzoY1pVA

@Gozala Something you had in mind?

**Comment by patrykadas** [comment]
https://youtu.be/cI0WfxN8rJU

Another iteration, still If I hover few links in short period of time it's glitching.

**Comment by patrykadas** [comment]
New link:
https://youtu.be/SUkQLclzx3A

I am not really satisfied with this one; I assumed that sending a request to verify if connection's safe may take a while and I came up with this circle - loading:

New link + target blank:
https://youtu.be/eH_U5ID-Ggo

Important things to notice:
Menu and the plus in the new header are appearing when user *clicked*
There is a circle near menu icon indicating that there is a new tab.
