### ISSUE TITLE
Include event.target for `mozbrowseroverscroll` events

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1258]
It would really help if we could include `event.target` for `mozbrowseroverscroll` events otherwise it is unclear which element is being scrolled, especially when there is nesting of overflowing elements. Even if only mozbrowser elements triggered those events it would be helpful to detect which one it is given that we maybe displaying multiple of them at the same time.

**Comment by paulrouget** [comment]
Target would be the element under the mouse. Isn't it always the iframe?

**Comment by paulrouget** [comment]
If overscroll can be triggered by any other part of the UI, that means I can't use a mozbrowser event and need to introduce a new type of DOM event.

**Comment by Gozala** [comment]
> Target would be the element under the mouse. Is it always an iframe?

That is not the case if I'm moving that iframe with an events.

> If overscroll can be triggered by any other part of the UI, that means I can't use a mozbrowser event and need to introduce a new type of DOM event.

> If overscroll can be triggered by any other part of the UI, that means I can't use a mozbrowser event and need to introduce a new type of DOM event.

I was under impression it was dispatch for all overflowing content, but probably I was wrong. Either way still would be very helpful to make `event.target` a specific iframe rather that relay on mouse being over it since we also put overlays with `pointer-events: none` and also move iframe with these events so it's not all that simple to get the target of the event.

**Comment by paulrouget** [comment]
Understood.

Let me describe the logic:

Scroll happens. Servo  sees if there's something to scroll under the mouse. If there's nothing to scroll, Servo finds the element under the mouse that is not `pointer-events:none`, and fire a overscroll event for that element. This event only happens for top level window (doesn't work within iframe), which means, the `<iframe>` will fire a overflow event.

**Comment by paulrouget** [comment]
I think we should fix this first: https://github.com/servo/servo/issues/1715

**Comment by Gozala** [comment]
There is no immediate plans for this work, so I'm just gonna close it
