### ISSUE TITLE
Grid layout should match mental navigation map

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1261]
Moving  @patrykadas's thoughts on the grid layout here so it's easier to discuss and collaborate:
## Building grid

<img width="368" alt="screen shot 2016-10-27 at 11 09 07 am" src="https://cloud.githubusercontent.com/assets/21236/19779424/ebd7b7f2-9c35-11e6-89c3-f78fb8f818d1.png">
#### Problem:

Impossible to understand, why I access the 2nd and 5th page by swipe right, and the rest of “tabs” by swipe down.

<img width="219" alt="screen shot 2016-10-27 at 11 11 20 am" src="https://cloud.githubusercontent.com/assets/21236/19779473/2093e470-9c36-11e6-91fd-835ea0744beb.png">
#### Problem:

What happens if I open from 2nd, 3rd of 4th few target:blanks?
If they stack below, we lose context.
### Building dynamic grid
1.  User is on the 1st page.
   <img width="238" alt="screen shot 2016-10-27 at 11 13 24 am" src="https://cloud.githubusercontent.com/assets/21236/19779589/936bccc4-9c36-11e6-9a24-05473f35dbe5.png">
2. User jumped on 3rd page from 1st page.
   <img width="239" alt="screen shot 2016-10-27 at 11 13 33 am" src="https://cloud.githubusercontent.com/assets/21236/19779596/9b600fa8-9c36-11e6-8359-5481c83f5658.png">
3. User jumped on 2nd page from 3rd page and wants to open three blanks.
   <img width="383" alt="screen shot 2016-10-27 at 11 13 40 am" src="https://cloud.githubusercontent.com/assets/21236/19779601/9ff702e2-9c36-11e6-8a07-d15973763d07.png">

**Comment by Gozala** [comment]
> Building grid
> 
> 
> 
> Problem:
> 
> Impossible to understand, why I access the 2nd and 5th page by swipe right, and the rest of “tabs” by swipe down.

So my interpretation of this is following:

***Premise:*** Let’s say user started navigation from **Page 1**. Then user navigated to **Page 2**, where clicking two `target=_blank` links opened ** Page 3** and **Page 4** in the background tabs. Then user switched to **Page 3** and navigated from there to  **Page 5**, where clicking another `target=_blank` link opened a **Page 6** in the background tab.

**Problem:** Now consider resulting grid. Swiping right reveals **Page 3** and **Page 1** which makes sense as it's how user got here. But swiping down would reveal **Page 6** and **Page 4**. 
**Page 4** seems counter intuitive is it has no correlation with **Page 5**.

P.S.: @patrykadas feel free to edit original issue description, so it will be obvious what's the problem is discussed in the issue without going through all the comments.

**Comment by Gozala** [comment]
> <img width="219" alt="screen shot 2016-10-27 at 11 11 20 am" src="https://cloud.githubusercontent.com/assets/21236/19779473/2093e470-9c36-11e6-91fd-835ea0744beb.png">

> #### Problem:

> What happens if I open from 2nd, 3rd of 4th few target:blanks?
If they stack below, we lose context.

My guess it further explains problem mentioned earlier, although I have hard time describing premise here. If you could write that down it would really help.

**Comment by Gozala** [comment]
The **Dynamic grid** section is not clear.

Let me try to describe what I see:

> ### Building dynamic grid

> -  User is on the 1st page.
    <img width="238" alt="screen shot 2016-10-27 at 11 13 24 am" src="https://cloud.githubusercontent.com/assets/21236/19779589/936bccc4-9c36-11e6-9a24-05473f35dbe5.png">

Same premise as in the previous comment

> - User jumped on 3rd page from 1st page.
    <img width="239" alt="screen shot 2016-10-27 at 11 13 33 am" src="https://cloud.githubusercontent.com/assets/21236/19779596/9b600fa8-9c36-11e6-8359-5481c83f5658.png">

I don't understand why **Page 1** is on the left, I guess because it is how you got to **Page 3** ? I think that is ok as long as it's visualized differently so it's clear that is a different tab which may in fact have it's own history.

> 3. User jumped on 2nd page from 3rd page and wants to open three blanks.
    <img width="383" alt="screen shot 2016-10-27 at 11 13 40 am" src="https://cloud.githubusercontent.com/assets/21236/19779601/9ff702e2-9c36-11e6-8a07-d15973763d07.png">

So I guess uncertainty here is where do those tabs get stacked ? I think the problem is with they way you draw the grid I think something along this lines would make it more clear:


<img width="1011" alt="screen shot 2016-10-27 at 11 13 11 am" src="https://cloud.githubusercontent.com/assets/21236/19781534/7d570324-9c3e-11e6-830d-e2576969190d.png">

**Comment by patrykadas** [comment]
Thank you for the comment! 

Basically, I think that I forgot to clarify that N is normal behavior (clicking a link) whereas B is target: blank or cntrl/cmd click. 

![zrzut ekranu 2016-10-28 o 10 42 33](https://cloud.githubusercontent.com/assets/6234032/19800263/435de670-9cfb-11e6-8ade-2b552e16857b.png)

In this example I've opened three Bs (target blanks) from this 1st website. As you may see, I spawned those websites on the right of 1st page, so theoretically to access target: blank I need to swipe right first to place myself in one of these websites, not bottom - up, which does not make sense. 

However, If we want to stack tabs vertically, like here:
![zrzut ekranu 2016-10-28 o 10 44 01](https://cloud.githubusercontent.com/assets/6234032/19800303/766f05d0-9cfb-11e6-8e61-c17f61304a16.png)

Then what happens after I switched to 2nd, 3rd or 4th website and want to open few target: blank pages from there? 

This is why I was thinking about grid to be dynamic:
![zrzut ekranu 2016-10-28 o 10 52 50](https://cloud.githubusercontent.com/assets/6234032/19800829/d8e011fe-9cfc-11e6-8615-b30c95d85917.png)

I've opened three target blanks from 1st website, then I jumped to the 3rd one instantly and during the moment of jump, 3rd page is taking place to the right of 1st page, which make sense, as 1st page is its ancestor. I just can't figure out yet how to proceed from then. Let's say I jumped to the 2nd page afterwards and opened few target: blanks from there. What happens with 4th website?

**Comment by patrykadas** [comment]
Main idea I want to stick to is the fact that horizontal movement is reserved for back - forward, and vertical one is for switching between something like "tabs", pages opened in the background.

Some ideas:

Grid #1
https://youtu.be/5mqUzaDNygk

Grid#2
https://youtu.be/onB5CYNSiHA

Grid#3
https://youtu.be/1521mW0BhrY

**Comment by patrykadas** [comment]
New version of grid, based on @Gozala comment, so we copy the current pages. The assumption is that if I care how I got to particular website, then I am only interested in one row, not the whole grid.

Grid:
https://youtu.be/MwQe17gAzjk

Corresponding menu:
https://youtu.be/ZZwgGczQqSA

**Comment by Gozala** [comment]
I am afraid my feedback was communicated with @patrykadas during conference call and some of it happened off channel on slack. I'll try to summarize it here though.

While I liked [Grid#3](https://youtu.be/1521mW0BhrY) I had some concerns in regards to a dynamic nature of the grid. More specifically if you following steps form  the posted video https://youtu.be/1521mW0BhrY?t=12s

__Numbers navigation history entries, brackets tabs with their navigation history and **!** character points to active tab__

Pages 3, 4 & 5 were spawned from page 2.

```
[1 2] !
  [3]
  [4]
  [5]
```

Activating page 4 causes following arrangement of the grid:

```
[1 2][4] !
     [3]
     [5]
```

I think this has following potential issues:

1. After **4** is activated sidebar will start displaying 3 rows instead 4 it used to, issue with that is same as in following bullets.
2. Order of tabs changes (for task oriented order) but there is big group of users that organizes tabs in specific order and uses that pattern to quickly jump between them. This goes agains such user flow.
3. If you consider case where user navigated to 10 more pages from 4. With such interface jumping to 2 becomes a lot more difficult which is not ideal in cases where page 2 maybe be an index or list.
4. If you close tab `[4]` do we move `[1 2]` back to the first row ? Regardless of the choice heuristics become to complex to have an intuition about it.


In discussion with @patrykadas I proposed to go slightly different route and instead of moving entries from the parent tab to the active child just create a pointer to the parent, or copy a history entries rather than moving (In terms of implementation it's going to be the same as we can't really copy history entries). We could also possibly use visual language like fading out `[1 2]` while placing non faded copy to the head of the `[4]` so that overall experience will be very similar to [Grid#3](https://youtu.be/1521mW0BhrY) but issue pointed out above won't be issues. I also suggested to ditch tab reordering as it's benefit is questionable while it's almost certain to be confusing for some users. With all this here is how above two steps could look like instead:

```
[1 2] !
  [3]
  [4]
  [5]
```

Activating page 4 causes following arrangement of the grid:

```
   [1 2]
     [3]
[1 2][4] !
     [5]
```

**Comment by Gozala** [comment]
> Grid:
> https://youtu.be/MwQe17gAzjk

Makes sense to me. What do you think ?

> Corresponding menu:
> https://youtu.be/ZZwgGczQqSA

_I can't tell from either video how `4` or `5` were spawned, so in the examples below I'll assume that `[4]` was open from page `1` and `5` was opened from page `2`. Also if I understand correctly `3` is opened from `2`._

Thoughts:

1. Looking at the grid you can't tell that `2` was spawned from `1`.
2. When `2` is selected `1` is not displayed on the right side of it, I would expect it to.
3. No trail for `4` or `5` is displayed, I think it would be useful to display that.

With that I think it menu will be far more useful if we displayed following:

**Number on the right of `|` character shows title / url of which page is displayed on the sidebar. `<` character shows page title that is selected. Character `:` in front of number means that page is being hovered.** 

```
       [1] | 1
    [1][2] | 2
[1][2][:3] | 3 <
    [1][4] | 4
 [1][2][5] | 5
```

I liked the sliding effect in the menu entries when hovering previous page. I would definitely do it when previous page is from the same tab. But if it is from the different tab like in this example I would suggest to select tab that page is actually from. So I would suggest instead of doing this:

```
       [1] | 1
    [1][2] | 2
[1][:2][3] | 2 < 
    [1][4] | 4
 [1][2][5] | 5
```


to do this:

```
       [1] | 1
    [1][2] | 2 <
[1][:2][3] | 3
    [1][4] | 4
 [1][2][5] | 5
```

Now that I wrote it I wonder what do you expect to happen when hovered `:2` is clicked ? Do we jump to a second tab from top ? Or do we pretend that you navigated back to `2` but stayed on the same tab ? I thought we'll do former, but now that I wrote this down I think later would be more intuitive, although it  may be little challenging in a following scenario:

```
         [1] | 1
    [1][2 3] | 2
[1][:2 3][4] | 2 <
```

As in reality we would have to actually display second tab and also navigate back, but if you switch to second tab we would have to navigate forward and it could get more challenging from there as many tabs could refer to different entries from different tabs :)

**P.S.:** Challenging does not mean we can't or should not do it :) I like challenge!

**Comment by patrykadas** [comment]
>Makes sense to me. What do you think ?

More I play with it and more grids I build, more I like it; definitely good direction :)

>I can't tell from either video how 4 or 5 were spawned, so in the examples below I'll assume that [4] was open from page 1 and 5 was opened from page 2. Also if I understand correctly 3 is opened from 2.

I wanted it to correspond with this video: https://youtu.be/MwQe17gAzjk

However, according to what you said there is one page missing in 3rd or 5th tab, as they could not be opened in the same time. If I'm not mistaken, this is how it got built:

![buildinggrid](https://cloud.githubusercontent.com/assets/6234032/20003642/f7d1572c-a287-11e6-9b18-e5c523e09e41.jpg)

In terms of showing the trail - I did not want to make it clumsy at first, If I spawned 4 /5 pages and I'd see more than 10, I'd be confused. After the menu is triggered I'd rather only show the current trial with active page, we can show other trails after the hover. 

Given our grid described above this is how it would look like:
![menu](https://cloud.githubusercontent.com/assets/6234032/20004689/121b29d6-a28e-11e6-8e48-414ede1c1bbf.jpg)

>Now that I wrote it I wonder what do you expect to happen when hovered :2 is clicked ? 

I was also thinking about this and so far came to same conclusions as you: 
![problem](https://cloud.githubusercontent.com/assets/6234032/20006742/456885bc-a299-11e6-9fdc-d5f18653dca7.jpg)
![problem2](https://cloud.githubusercontent.com/assets/6234032/20006743/456be5e0-a299-11e6-9041-3e5d5983ffb6.jpg)

but I keep thinking about it, I am preparing different prototypes of the interface itself and display of the grid.

**Comment by patrykadas** [comment]
1) Grid that shows correlation, if two pages are the same within visible canvas:
https://youtu.be/IOCROVLgQaA

2) Grid without showing correlation between pages:
https://youtu.be/nLyHl2vX4X4

3) New page 
https://youtu.be/tTkx-5aY22M

I thought it would be nice if we could create new page two ways: 
Create new path, without correlation to any other pages; clean state.
Create page in correlation to existing path (plus button next to latest page)

4) Make it feel more organic
Also, in terms of visual aspect I really wanted to make the grid more „organic”, as its continuous stream of constantly fluctuating data. I thought we could do some small tweaks to communicate it:

One page within grid:
http://share.framerjs.com/t71oehtd6q7f/

Applied on grid:
https://youtu.be/OEfol9QQj7U

I think it’s engaging, pages tend to really want to play with you. Currently it happens on :hover, but it could happen on click and move and page open on release.

5) Force touch used to take a look from the distance
https://youtu.be/ah0gOAGnB3E

On force touch start I zoomed out the pages, on force touch end I zoomed them in again. It’s just for a preview in this case.

6) Force touch organic? 
https://youtu.be/ez5xV2-SaGA 
I treat it as failed experiment, however worth seeing.

**Comment by Gozala** [comment]
> I wanted it to correspond with this video: https://youtu.be/MwQe17gAzjk

I see, let follow the scenario I have outlined though as I think it covers more edge cases.

> However, according to what you said there is one page missing in 3rd or 5th tab, as they could not be opened in the same time. If I'm not mistaken, this is how it got built:

This are the steps:

```
[1] | 1 <
```
```
   [1] | 1 <
[1][2] | 2
```

```
   [1] | 1
[1][2] | 2 <
```

```
      [1] | 1
   [1][2] | 2 <
[1][2][3] | 3
```

```
      [1] | 1
   [1][2] | 2
[1][2][3] | 3 <
```

```
      [1] | 1 <
   [1][2] | 2
[1][2][3] | 3
```

```
      [1] | 1
   [1][2] | 2
[1][2][3] | 3
   [1][4] | 4 <
```

```
      [1] | 1
   [1][2] | 2 <
[1][2][3] | 3
   [1][4] | 4
```

```
      [1] | 1
   [1][2] | 2
[1][2][3] | 3
   [1][4] | 4
[1][2][5] | 5 <
```


> In terms of showing the trail - I did not want to make it clumsy at first, If I spawned 4 /5 pages and I'd see more than 10, I'd be confused. After the menu is triggered I'd rather only show the current trial with active page, we can show other trails after the hover.

What about history of the current tab vs the tabs that got you there ? More specifically let's consider following version instead:


```
[1] | 1 <
```
```
[1 2] | 2 <
```

```
[1 2 3] | 3 <
```

```
   [1 2 3] | 3
[1 2 3][4] | 4 <
```

```
     [1 2 3] | 3
[1 2 3][4 5] | 5 <
```
```
        [1 2 3] | 3
   [1 2 3][4 5] | 5
[1 2 3][4 5][6] | 6 <
```

I can get behind not wanting to show duplicate pages all over, but then I also would expect to see tab history at the very least. So maybe see something like:

```
        [1 2 3] | 3
          [4 5] | 5
[1 2 3][4 5][6] | 6 <
```

Alternatively maybe stacking those pages could be a nice way to show there's more stuff but we don't want to overwhelm you with details, something like:

__Note: `[..]` represents stack

```
        [1 2 3] | 3
      [..][4 5] | 5
[1 2 3][4 5][6] | 6 <
```

Or even less detailed version where you can only see top of the stack, maybe half of the second page and that there is more underneath:

```
       [.. 2 3] | 3
       [.. 4 5] | 5
[1 2 3][4 5][6] | 6 <
```

That way when you hover the tab we could also unfold the stack, something along this lines http://tympanus.net/Development/IsometricGrids/


> 1) Grid that shows correlation, if two pages are the same within visible canvas:

I am starting to think that showing correlation isn't actually important if when I go to that page it will feel as if I went back rather than switched tabs, which I think what would make most sense IMO.

> 3) New page 

Looks neat, but then what happens if you zoom out ? Do you get to keep blank page ? I really like how current ui prevents you from creating bunch of duplicate blank pages. I really hope we can keep that.

I don't like that "new path" now is the at the bottom of the tab list I think it makes it more difficult to discover especially if you have long list of tabs. BTW what is the reason we are changing the order in which new tabs are added, currently it's added to the top in all these demos it's at the bottom.

> 5) Force touch used to take a look from the distance

I would just use pinch gestures for that like rest of the OSX does it.

I would use force touch to unfold stacks if we end up creating those.


What happens in this scenario:

```
        [1 2 3] | 3
   [1 2 3][4 5] | 5 <
[1 2 3][4 5][6] | 6
```

Triggered goBack (reflected in title in the sidebar)

```
        [1 2 3] | 3
   [1 2 3][4 5] | 4 <
[1 2 3][4 5][6] | 6
```

Then clicked a regular link that navigates to page `7`. It's either we fork regardless (which I think makes most sense but can be a real challenge to implement).

```
        [1 2 3] | 3
   [1 2 3][4 5] | 5
   [1 2 3][4 7] | 7 <
[1 2 3][4 5][6] | 6
```

or we just follow the current browser behavior:

```
        [1 2 3] | 3
   [1 2 3][4 7] | 7 <
[1 2 3][4 5][6] | 6
```

But then it's not only would feel odd, it also would introduce a problem of third tab containing page `5` 
that no longer exists anywhere so it's same challenge as in forking solution.


@patrykadas I think it would also be useful to display groupings per path. So that in case of `[1 2 3][4 7]` user could tell that `[1 2 3]` happened in one session and then `[4 7]` happened in the forked session.

**Comment by paulrouget** [comment]
So as I understand it, we are decorrelating internal history and user history. That's fine.

What we manipulate here are references to pages, right?
When we copy pages, we copy references?
Are, at any point, alive pages being cloned?

To your mockups/graph, can you please add these information:
- is the page frozen or not (is the page still running, think of soundcloud for example, is sound still playing in the background?)
- internal history right and left sibling (from the point of view of the page, calling `window.history.goBack()`, which page gets activated?)
- on the side, a list of active pages (or maybe these are always the pages we see on the right of the `|`)

Does, at any point, the internal history gets manipulates (does calling `window.history.goBack()` change when the page are copied)?

**Comment by patrykadas** [comment]
I would like @Gozala to comment, but here are my thoughts:

>What we manipulate here are references to pages, right?
Right.

>When we copy pages, we copy references?
Right; references, shortcuts. 

>Are, at any point, alive pages being cloned?
Not sure about this one, but I'd say no.

Force touch causing expansion of the stack:
https://youtu.be/zwcRqYNLbfM

**Comment by Gozala** [comment]
> So as I understand it, we are decorrelating internal history and user history. That's fine.
> 

Yeah so we're trying to present navigation trail for tab that may pan across multiple other tabs. Idea is that single row would show you every step you did to get there regardless of how many tabs were created in the process.

> 
> What we manipulate here are references to pages, right?

I'd say references to history entries, but I think we're referring to the same thing.

> When we copy pages, we copy references?

More like we create pointers to the history entry, and they point to a history entries  in a different tab.

> Are, at any point, alive pages being cloned?
>

That is implementation detail. Can we even clone them ? So problem with pointers to history entries in the different tab are:

1. What if user closes that tab ?
2. What if user goes back and then takes a different path killing of the branch ? What are we pointing to then ? I guess our option will be to rewrite history for that tab and update all the pointers accordingly, not ideal but as far as I can tell still possible with proposed API.
 
>
> To your mockups/graph, can you please add these information:
> 
> is the page frozen or not (is the page still running, think of soundcloud for example, is sound still playing in the background?)

Only pages that appear in the sidebar (pages that match numbers after `|` ) are running.

That is actually a problem in this scenario:


```
        [1 2 3] | 3
   [1 2 3][4 7] | 7 <
[1 2 3][4 5][6] | 6
```

User returned to / selected page `2` in the second tab

```
        [1 2 3] | 3
   [1 2 3][4 7] | 2 <
[1 2 3][4 5][6] | 6
```

Now two history entries from the first tab are supposedly active at the same time. I was thinking of freezing `3` and activating `2` in this scenario since user is going to see `2` anyway but if music is playing in page `3` that does not seem like a good option.

Is there something better we could do ?

> internal history right and left sibling (from the point of view of the page, calling window.history.goBack(), which page gets activated?)

So if `3` calls `window.history.goBack()` I don't see how user would reach page `4` in first place. But let's suppose clicking a button on page `3` does `window.history.goBack()`. Let's consider two different scenarios depending on which tab is active:

### Scenario 1.

```
        [1 2 3] | 3 <
   [1 2 3][4 7] | 2
[1 2 3][4 5][6] | 6
```

Click

```
        [1 2 3] | 2 <
   [1 2 3][4 7] | 2
[1 2 3][4 5][6] | 6
```

User clicks link that navigates to page `8` we fork a path:

```
        [1 2 3] | 2
       [1 2][8] | 8 <
   [1 2 3][4 7] | 2
[1 2 3][4 5][6] | 6
```

Or maybe we just alter the path

```
        [1 2 8] | 8 <
   [1 2 3][4 7] | 2
[1 2 3][4 5][6] | 6
```
What do you thing @patrykadas 

### Scenario 2.

```
        [1 2 3] | 3
   [1 2 3][4 7] | 7 <
[1 2 3][4 5][6] | 6
```

Activate Page `3` in the active tab.

```
        [1 2 3] | 3
   [1 2 3][4 7] | 3 <
[1 2 3][4 5][6] | 6
```
Click `goBack` button:
_Note: First tab still shows page `3` and if you activate it we'd have to activate that page again.

```
        [1 2 3] | 3
   [1 2 3][4 7] | 2 <
[1 2 3][4 5][6] | 6
```

User clicks link that navigates to page `8` we fork a new path:

```
        [1 2 3] | 3
   [1 2 3][4 7] | 2
       [1 2][8] | 8 <
[1 2 3][4 5][6] | 6
```

Or alternatively we alter the second tabs path:

```
        [1 2 3] | 3
       [1 2][8] | 8 <
[1 2 3][4 5][6] | 6
```

I'm leaning towards forking vs altering although argument can be made `cmd / ctrl` click provides an option to fork so maybe altering is better option. I'd say let's leave this question open for now I don't think it's really changing much in terms of embedding.

> on the side, a list of active pages (or maybe these are always the pages we see on the right of the |)

On the side is list of tabs and more specifically page that is currently active with in that tab. Well idea is that users would think of them same as tabs but in reality they're something else let's call them "paths" or "trails" as they are list of pointers to history entries across different webviews / browsers / tabs.

> Does, at any point, the internal history gets manipulates (does calling window.history.goBack() change when the page are copied)?

I'm not sure I totally follow the question here, maybe my answer above about `window.history.goBack()` covers it ? 

Give last version of embedding API I've read I think only way to do this would be to always prevent servo from altering history and instead push new entries to the end of the list. That way pointers cross different paths / trails can reliably point to entry by index from the head of the list. Also our paths / trails would be pretty much list of pointers to history entries across different browsers not the browsers themselves. So when user activates page we would just activate history entry it points to in the corresponding browser. 

Unresolved issue is what do we do if multiple entries from the same browser appear active in the sidebar ? More specifically what if one of them or multiple of them also play media ?

**Comment by paulrouget** [comment]
> What if user goes back and then takes a different path killing of the branch ? What are we pointing to then ? I guess our option will be to rewrite history for that tab and update all the pointers accordingly, not ideal but as far as I can tell still possible with proposed API.

You save the list of LoadData. Which can be re-used to recreate a branch. You kill whatever branch you want by either saving the forward-LoadData and following the link normally, or interrupt navigation and create a new browser with the back-LoadData. Anyway. It's possible with the new API. It's not ideal (poor performance), but it's good enough for prototyping.

> Now two history entries from the first tab are supposedly active at the same time. I was thinking of freezing 3 and activating 2 in this scenario since user is going to see 2 anyway but if music is playing in page 3 that does not seem like a good option.

You can clone history branches. That will do for prototyping.

**Comment by Gozala** [comment]
I think given the [posted overview](https://medium.freecodecamp.com/lossless-web-navigation-with-trails-9cd48c0abb56) we can mark this fixed.
