### ISSUE TITLE
Creating tasks, taking notes, and making reports

### ISSUE THREAD

**Issue by timthelion** [browserhtml/browserhtml#1265]
Hello,
sorry for jumping in like this without knowing much about the project. I saw a medium post here: https://medium.com/@patrykadas/lossless-web-navigation-with-trails-9cd48c0abb56#.mxynkvyyo and I was imediately hit by two feelings "awsome" and "aw darn, not quite".

So I'm going to tell you a little story, about what I did using Firefox over the last couple of days, embellished a little, and kinda sci-fi.

So over the past couple of days I've been planning my trip to FOSDEM in Brussels https://fosdem.org/2017/. I needed to get a plane ticket, a hotel room, and look up some tasty Vegan restaurants.

So I opened up a new "paths workspace" in Firefox and titled it FOSDEM 2017.

I was now interacting with something that looked like org-mode. A tree view, in which the root entry was "FOSDEM 2017".

I then created 3 subnodes:

````
FOSDEM 2017
- Book plane tickets to Brussels
- Book Hotel Brussels
- Find vegan restaurants Brussels
````

After having entered these three items, I right clicked on "Book plane tickets to Brussels" I was greated by a search dropdown asking me which search engine I wanted to use. I chose gooogle.

A new tab was opened for google, but there was still a tab in the background with my FOSDEM workspace open. If I switched back to the FOSDEM workspace I would see:

````
FOSDEM 2017
- Book plane tickets to Brussels
-- Search Google for "Book plane tickets to Brussels"
- Book Hotel Brussels
- Find vegan restaurants Brussels
````

I clicked on the first result and began to fill out the form for the airplane search engine. I opened two more tabs to view two flights that looked good. For each flight, I pressed "bookmark" and added a note on how much it cost and when it left/arrived. And then switched back to the FOSDEM. What I saw was this:

````
FOSDEM 2017
- Book plane tickets to Brussels
-- Search Google for "Book plane tickets to Brussels"
--- Cheep Plane tickets.com
---- Search for pane tickets to Brussels 3.2-6.2 2017
----- Ryan air flight 3345
Notes: 2000CZK leaves 8:45am arrives to Charelroi
----- Czech Airlines flight 3948
Notes: 3000CZK leaves 6:30am arrives to Brussels National
- Book Hotel Brussels
- Find vegan restaurants Brussels
````

Then I clicked on the "-- Search Google for "Book plane tickets to Brussels" tree item and was transported back to the google search results. I looked at another ticket search engine and got slightly different results. I opened one of them and booked marked it with a similar note. My FOSDEM workspace now looked like:

````
FOSDEM 2017
- Book plane tickets to Brussels
-- Search Google for "Book plane tickets to Brussels"
--- Cheep Plane tickets.com
---- Search for pane tickets to Brussels 3.2-6.2 2017
----- Ryan air flight 3345
Notes: 2000CZK leaves 8:45am arrives to Charelroi
----- Czech Airlines flight 3948
Notes: 3000CZK leaves 6:30am arrives to Brussels National
--- Super duper cheep pane tickets.eu
---- Search for pane tickets to Brussels 3.2-6.2 2017
----- Brussels airlines flight 7779
Notes: 2300CZK leaves 12:01am arrives to Brussels National
- Book Hotel Brussels
- Find vegan restaurants Brussels
````

I hummed and hawed a bit, and realized that with the cost of getting from Charleroi to Brussels, and the time it takes, the fastest and cheepest flight was "----- Brussels airlines flight 7779". I clicked on that link again, whent through the dialogs to book my flight, and then went back to the FOSDEM workspace.

````
FOSDEM 2017
- Book plane tickets to Brussels
-- Search Google for "Book plane tickets to Brussels"
--- Cheep Plane tickets.com
---- Search for pane tickets to Brussels 3.2-6.2 2017
----- Ryan air flight 3345
Notes: 2000CZK leaves 8:45am arrives to Charelroi
----- Czech Airlines flight 3948
Notes: 3000CZK leaves 6:30am arrives to Brussels National
--- Super duper cheep pane tickets.eu
---- Search for pane tickets to Brussels 3.2-6.2 2017
----- Brussels airlines flight 7779
Notes: 2300CZK leaves 12:01am arrives to Brussels National
------ Brussles airlines flight 7779 enter your credit card info
------- Brussles airlines flight 7779 enter your boarding pass
- Book Hotel Brussels
- Find vegan restaurants Brussels
````

I then clicked on the left side of  "------- Brussles airlines flight 7779 enter your boarding pass". The whole line turned green and a checkmark appeared besides it. I then clicked on a "fold" symbol besides "- Book plane tickets to Brussels" and saw:

````
FOSDEM 2017
+ Book plane tickets to Brussels
✓ Brussles airlines flight 7779 enter your boarding pass
- Book Hotel Brussels
- Find vegan restaurants Brussels
````

I then moved on to booking a place to stay.

The only difference was, that I didn't just search for "Book Hotel Brussles" I manually added 4 subitems:

````
FOSDEM 2017
+ Book plane tickets to Brussels
✓ Brussles airlines flight 7779 enter your boarding pass
- Book Hotel Brussels
-- couchsurfing.com
-- Hostels Brussels
-- Airbnb.com
-- Wimdu.com
-- Hotels Brussels
- Find vegan restaurants Brussels
````

Adding many notes along the way and editing those notes, not just using the bookmark button, but by switching back to the "FOSDEM" workspace after having searched on the map how long it takes to get to ULB university from the rooms.

Finally I arrived at:

````
FOSDEM 2017
+ Book plane tickets to Brussels
✓ Brussles airlines flight 7779 enter your boarding pass
+ Book Hotel Brussels
✓ Airbnb, your room has been booked!
- Find vegan restaurants Brussels
````

And finally I searched for Vegan restaurants nearby and selected a couple that I thought looked nice.

````
FOSDEM 2017
+ Book plane tickets to Brussels
✓ Brussles airlines flight 7779 enter your boarding pass
+ Book Hotel Brussels
✓ Airbnb, your room has been booked!
+ Find vegan restaurants Brussels
✓ Lu Wee Vegan
Cheep asian. Close by
✓ Rara Vegelele
Looks like an experience, kinda outof my price range, but I'm only in Brussels once a year. Monday maybe?
✓ Bulk and Sandwich cafe
Not just vegan, some things have cheese. Get snacks here.
````

Then. Once I was done planning my trip. I clicked on the "create report button". A nice LATEX quality PDF was generated and saved to my hard drive. It had a Title page "FOSDEM 2017". The next page contained my boarding pass to get on the plane. The next page had my booking code and the adress of the Airbnb. Finally, it contained screenshots of the contact page for the 3 vegan restaurants I had chosen. And of course, for the ✓'ed items, the notes were included too.

**Comment by Gozala** [comment]
Hi @timthelion thanks for sharing your story. I do have little difficulty of interpreting it as feedback though. My guess at this point is you want a browser that supports task list style interaction use case. Good news is @patrykadas has some thoughts ideas we'd like to explore that attempt to address that use case. That being said that exploration is not a very high on our priority list right now as we attempt to work on more common browsing issues as described in the post.

If I'm misunderstanding your comment, please elaborate and put it in the context otherwise it's hard for us to act on this issue in any way.

Thanks

**Comment by timthelion** [comment]
It wasn't meant as feedback really. I'm glad that you are working on
making the browser history more understandable, as it is one of the
browser features that I have a lot of trouble with. (Even just grouping
the history by domain would be a huge help.) My story was just me
dreaming, nothing more...
