### ISSUE TITLE
trails? sounds familiar :)

### ISSUE THREAD

**Issue by grindhold** [browserhtml/browserhtml#1266]
hai guise!

have u heard of my browser?
http://rainbow-lollipop.de/
https://github.com/grindhold/rainbow-lollipop

**Comment by vsinha** [comment]
any news on the OSX port of this? would love to test it out

**Comment by grindhold** [comment]
development is currently frozen. waiting for the next gtk release with gsk merged in it. developing further now is wasted time because libclutter (which a big portion of the ui is based upon) will become legacy. from then on porting shouldn't be too hard.
