### ISSUE TITLE
mach script should check for dependencies

### ISSUE THREAD

**Issue by Oregon-Tech-Ninja** [browserhtml/browserhtml#1270]
The ./mach build command should check for dependencies and avoid downloading anything unnecessary. It downloaded rust and cargo on my system, and I have rustup with a few versions of rust already installed.

**Comment by cbrewster** [comment]
This seems more of a servo issue and should be filed as an issue there. That being said, servo uses a pinned version of rust nightly which is why you probably had to download it (as you may not have had the specific pinned nightly version installed already).

**Comment by Gozala** [comment]
Closing as it indeed belongs on the servo project. There today there's a no option of just downloading pre-built servo & using it instead of ./mach
