### ISSUE TITLE
Integrate prettier into toolchain to deal with code formatting.

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1271]
It would be nice to incorporate [prettier][] into our toolchain as [standardjs][] still allows variety of awkward formatting as it was made evident by changes in #1269.

Please note, that I don't suggest ditching [standardjs][] and switching to a completely new format (not right now anyway). [standardjs][] enforces more than just formatting rules, so let's keep it around for now & incorporate [prettier][] as per prettier/prettier#736

[standardjs]:http://standardjs.com/
[prettier]:https://github.com/prettier/prettier

**Comment by Gozala** [comment]
@magopian is this something you'd be interested in tackling ?

**Comment by magopian** [comment]
I'm not sure, it seems there's no support in `prettier` to not have semicolons yet (i tried `prettier-eslint` but couldn't install/make `leveldown` locally without errors).

**Comment by Gozala** [comment]
> (i tried prettier-eslint but couldn't install/make leveldown locally without errors).

That's unfortunate I might give it a try at some point.

**Comment by Gozala** [comment]
I'm closing this as there are no immediate plans to work on this, if someone want's to tackle this please speak up & I'll reopen.
