### ISSUE TITLE
Design explorations 

### ISSUE THREAD

**Issue by patrykadas** [browserhtml/browserhtml#1273]
Some of the sources:

Hypothesis entry about it:
https://hypothes.is/blog/annotation-is-now-a-web-standard/

List of services from the past:
https://docs.google.com/spreadsheets/d/1f86L7vgHUW9wSLNNSunhjmtxtg6KlCOVpHGKbqUzW-Y/edit#gid=0

Very nice research:
http://zesty.ca/crit/yee-crit-cscw2002-demo.pdf

## Problems

Currently, our design uses spatial model: horizontal movement is used for going back / forward, whereas vertical is for switching trails. https://github.com/browserhtml/browserhtml/issues/1261

1) [Trail view](https://www.youtube.com/watch?v=AWpbnV41zUE) is a zoomed-out page, therefore we also operate in Z-Axis. As we right - align the pages in the trail view, we can’t say how they corelate to each other time-wise. Time stamp we see is not real, pages are aligned in particular sequence, but it does not mean that last page from first trail was used in the same time as last page from second trail.

2) There are many services that help us to save content we find interesting, however I could not find any that would corelate the content I found to the context of my search. 

> The feed massively increased the visibility of your network on Facebook, and helped raise the profile of stories that were being shared by millions of people in real time. But this came with a cost: These stories were stripped of their original context. If the organizing principle of the broadcast schedule was synchronization — millions seeing the same thing at the same time — then the organizing principle of the stream is de-contextualization — stories stripped of their original context, and organized into millions of individual, highly personalized streams.
[Full story](https://howwegettonext.com/the-schedule-and-the-stream-eb1e9a7a344a)

## Possible solution

**I want to utilize Z-Axis to show both: web history and annotated content with trails.** 

https://youtu.be/0EuvP9vuO44

In this scenario, there are basically three levels of zoom:
1) A web page (in this case: vimeo)
2) Trail view
3) History / annotations view

After reaching 3rd level, I think it would be useful to be able to adjust it a bit more. 

Elements of this view:
![list](https://cloud.githubusercontent.com/assets/6234032/24655144/4b6c177e-193d-11e7-8d97-dfe04a361d1c.png)

Annotated content could be a media (video / static image / gif), a text (headline, paragraph) or a link. 

![map](https://cloud.githubusercontent.com/assets/6234032/24655254/d1ad3930-193d-11e7-809e-8d5e0ff63643.png)

Positions are displayed chronologically. Pages with same domains are grouped together. It's just a quick visualisation, therefore there are many things to be solved. Background color of the title corelates to the accent color of the website. 

On the bottom there is a slider. I would like it work like the one in animation software: I can not only move it around, but I can also stretch the toggle itself. **Wider the toggle, more 'zoomed out' the view.** 

Hovering annotation from the list would also show its position within trail. 

That's just an early exploration of this idea, but I'd love to receive feedback as soon as possible.

**Comment by Treora** [comment]
Great you are exploring this, I am curious where it will head towards, as I am struggling with similar ideas. I will gladly share some thoughts, perhaps any of them may of use to you.

I love the zoomable timeline visualisation that clusters pages from the same domain. I [started](https://github.com/WebMemex/webmemex-extension/commit/500cb0a46bde5d8358fae4b45bd7444c2bc2cafd#diff-f1fdaed52bd5206d18e903cf372ee395R12) clustering visited pages by domain as well, but found it often badly matches my mental model of page relatedness. I wonder if you also have plans to cluster by vicinity in time&trail, and/or to group whole trails, browser sessions or topic-based clusters when zooming out further.

Regarding 'annotation', does the design include the possibility for a user's own creations, e.g. notes that one writes about a page or paragraph? Or is that out of scope, and is the focus here on displaying selected 'highlights' (annotation targets without annotation bodies, in Web Annotation parlance)?

In either case, I wonder what the idea of the list of annotations on the side is. Does it list all content that the user highlighted/annotated, to easily find it back? Would this be a timeline itself? Is the list context-dependent?

I have been thinking myself to make a time line that shows everything: larger symbols for the pages one bookmarked, selections one highlighted, notes one created; and smaller symbols for other pages one visited, whose trails would merely be a network connecting all everything together. When zoomed in, e.g. looking at the most recent hour, one would see the full browsing history; when zoomed out, one would only see the more important (e.g. bookmarked) items, while the other pages would have disappeared or have become dots on the paths connecting those displayed items.

**Comment by patrykadas** [comment]
@Treora Thank you for the comment! This is just an initial idea and there is still plenty to figure out.

> I wonder if you also have plans to cluster by vicinity in time&trail, and/or to group whole trails, browser sessions or topic-based clusters when zooming out further.

That was also an issue brought by @Gozala, to make it more objective - oriented. Yes, I'm trying to figure out nice way to have it arranged by sessions, but also make it possible to connect things outside of those. 
https://workflowy.com/demo/embed/
Workflowy utilizes tags for this purpose, but I am afraid that users may not do that.


> Regarding 'annotation', does the design include the possibility for a user's own creations, e.g. notes that one writes about a page or paragraph?
I have not included it in the designs, but it is in the scope.

> Or is that out of scope, and is the focus here on displaying selected 'highlights' (annotation targets without annotation bodies, in Web Annotation parlance)?
But yes - for now It would be best to start small and for now just focus on saving content. 

> In either case, I wonder what the idea of the list of annotations on the side is. Does it list all content that the user highlighted/annotated, to easily find it back? Would this be a timeline itself? Is the list context-dependent?
For now I wanted it to be a shortcut / summary to all the annotations that user has done, so it's easy to find back. It would remind an interface of, for example Airbnb, where listings are corelating to the map, making it context - dependent, unless we have space to display more annotations than within the map - then hovering a position in the list that's outside of the map would move the map. 


> I have been thinking myself to make a time line that shows everything: larger symbols for the pages one bookmarked, selections one highlighted, notes one created; and smaller symbols for other pages one visited, whose trails would merely be a network connecting all everything together. When zoomed in, e.g. looking at the most recent hour, one would see the full browsing history; when zoomed out, one would only see the more important (e.g. bookmarked) items, while the other pages would have disappeared or have become dots on the paths connecting those displayed items.

Exactly, basically it could all operate within Z-Axis, with particular breakpoints (100% - a page, 50% with a perspective - trail view, 49% - 1% history view / annotations). However, it causes lots of troubles and many, many edge case scenarios that have to be taken care of. Also, I'm not sure if it's intuitive and easy to grasp given the excessive amount of information. I think it's the matter what's more important: content or its context and how to balance this.

**Comment by patrykadas** [comment]
I have decided to move the conversation below, not to create additional noise in the issues:
https://drive.google.com/drive/folders/0B8pr60831MlMd291N0tndURLV3c?usp=sharing

Feel free to comment within google docs, I will be updating those documents whenever something new shows up.
