### ISSUE TITLE
ContentScript for browser.html in WebExtensions manifest file

### ISSUE THREAD

**Issue by lukaszpolowczyk** [browserhtml/browserhtml#1291]
Please support this bug, it is crucial for the survival of Firefox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1356521

Understand that well. There are people who want to have every little thing adjusted. Blocking this API causes you to make this absurd. People will start to make Firefox forks, which will be some minor changes! This is what you will get rid of. Can not you see this absurdity?

The only thing that can save us is the Unbranded version that will not block full extensions.

Theoretically you can do:
"Content_scripts": [
{{
"Matches": ["chrome://browser.html", "chrome://bookmarksPanel.html"],
"Js": ["realExtenson.js"]
}
]

Where chrome://browser.html represents the main browser window, chrome://bookmarksPanel.html represents the default (built-in) bookmark panel. The realExtension.js file would have access to the WebExtensions API and to every function, command, or interface that the browser has access to.
Similarly, you could load CSS files.

But from what I know, they are NOT willing to give you such a possibility, because the Firefox user will set up as he installs his extension and it turns out that something has changed. Extensions have nothing to change. : |
Somehow so far they change, and nothing bad happens.

**Comment by tschneidereit** [comment]
This project is unrelated to Firefox and to WebExtensions, so there's nothing we can do here.
