### ISSUE TITLE
run browser.html with the servo binary?

### ISSUE THREAD

**Issue by darkbasic** [browserhtml/browserhtml#1293]
I use Archlinux and I installed servo-git from AUR. I also cloned browserhtml. Any chance to run browser.html using the servo binary? I cannot run ./mach from the source tree...

**Comment by paulrouget** [comment]
Yes. See https://github.com/browserhtml/browserhtml#developing-the-front-end

Instead of `./mach run -r -- `, use `servo`.

**Comment by darkbasic** [comment]
Thanks, it "works". It seems Servo is still way more unusable than I expected: simply typing something in the search bar is enough to get it unresponsive. I managed to render a part of a webpage just once.
