### ISSUE TITLE
Windows: Backspace does not work consistently

### ISSUE THREAD

**Issue by SaschaNaz** [browserhtml/browserhtml#1294]
Moved from https://github.com/servo/servo/issues/16599:

1. Type github.com
2. Long-press backspace key
3. Deleted characters randomly reappears

![servo-backspace](https://cloud.githubusercontent.com/assets/3396686/25370986/3b23a93a-29c9-11e7-9b1b-2978488b04ef.gif)

**Comment by Gozala** [comment]
@SaschaNaz I'm unable to reproduce it on my machine, although I don't have a windows box around to test this. It also maybe be just another instance of #1292 could you please try reproducing this by trying it offline (that way you won't get an autocomplete) and we'll know for sure if it's autocomplete that causes this or if it's something windows specific.

Thanks

**Comment by SaschaNaz** [comment]
Sorry to respond too late, yes I cannot reproduce this with network disabled. So this is a duplicated issue and I'll close this :smile:
