### ISSUE TITLE
embedding

### ISSUE THREAD

**Issue by gedw99** [browserhtml/browserhtml#1309]
So i tried the servo build. It owrks and is still rough around the edges.
But i would like to be able to compile servo into a desktop app using rust or golang.
I currently use Electron and webviews, but i think servo is the future and woudl like to try to get something going.
Any advice ?

For example riht now its very easy to embed servo inside another golang app, and when the golang app starts, kick off servo. But for graphic apps this just does not cut the mustard well enough because you end up opening 2 GUI apps in reality etc.

SO is there any ideas on how to embed servo inside a golang app ?

**Comment by Gozala** [comment]
@gedw99 I sadly don't know of anyone doing embedding in go but if anyone @paulrouget is probably a person to talk to, he embedded servo into bunch of different ways.

As of Electron like runtime but with servo @tschneidereit might have some details.

**Comment by Gozala** [comment]
@gedw99 I would also suggest dropping by  think #webembedding on irc.mozilla.com

**Comment by paulrouget** [comment]
@gedw99 please see https://github.com/paulrouget/servo-embedding-example

**Comment by paulrouget** [comment]
> SO is there any ideas on how to embed servo inside a golang app ?

Build Servo as a library, and open it dynamically. Here is another example: https://github.com/paulrouget/servofocus
