### ISSUE TITLE
Graphene won't lunch with default OSX config

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#233]
![screen shot 2015-03-12 at 10 51 38](https://cloud.githubusercontent.com/assets/21236/6624333/d9949da4-c8a5-11e4-80cd-74c532db206c.png)

This what you'll get when you double click on the B2G 

In order to lunch it you need to go to System preferences > Security & Privacy

And click "Open Anyway" button as shown in the screenshot

![screen shot 2015-03-12 at 10 53 33](https://cloud.githubusercontent.com/assets/21236/6624404/2e11019c-c8a6-11e4-9413-bb17f14e74e2.png)

**Comment by gordonbrander** [comment]
Adding to milestone. Determine if we can do anything about this, but don't spend too much time on it.

**Comment by gordonbrander** [comment]
Update: we can't really work around until we do proper packaging.

**Comment by paulrouget** [comment]
Actually… I think the build by releng are signed.

**Comment by paulrouget** [comment]
Nope.
