### ISSUE TITLE
When webView.uri changes, we should reset the whole webview

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#345]
Today, if we change the `uri` attribute, `isLoading` is still `false`, and many other properties don't make sense.

**Comment by Gozala** [comment]
@paulrouget don't we get a load start event for that ?

**Comment by paulrouget** [comment]
It happens too late. There's this short window of time (~100ms) where the the webview is not loading but the URL has changed. This creates some UI glitches.
