### ISSUE TITLE
App "forgets" link that launched it

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#393]
With browser.html closed, click on a link outside of browser.html (in a Twitter client or email app, for example).

What happens: browser.html launches, but does not "remember" the link.

What should happen: browser.html launches and a new tab is opened for the link.

**Comment by paulrouget** [comment]
Restore happens after loading the `-url` url I guess.

**Comment by paulrouget** [comment]
Note to self: chrome event arrives too early.

**Comment by Gozala** [comment]
BTW it seems that OSX does not allow setting `Browser.html.app` as a default browser, I presume that has something to do with `.html` in the application name.
