### ISSUE TITLE
about: 404

### ISSUE THREAD

**Issue by tpimh** [browserhtml/browserhtml#428]
https://github.com/mozilla/mozilla.github.io/issues/7

`about:config` redirects to `https://mozilla.github.io/browser.html/src/about/config/index.html` which does not exist.

**Comment by gordonbrander** [comment]
We haven't implemented 404 handling yet, but even so that's a pretty strange result :). cc @paulrouget

**Comment by paulrouget** [comment]
meh

**Comment by paulrouget** [comment]
Oh yes. That' because we rewrite `about:xxx` to `https://mozilla.github.io/browser.html/src/about/xxx/index.html`.

**Comment by tpimh** [comment]
Yes, I see it's rewritten. But why?

**Comment by paulrouget** [comment]
Because our `about:xxx` handler is lame.
