### ISSUE TITLE
Implement right-click menu

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#503]
Contains back/fwd/refresh controls as well as others, later.
Part of perspective-ui that has not yet been implemented.

**Comment by paulrouget** [comment]
We get the contextmenu event and we now have the mouse coordinates (https://bugzilla.mozilla.org/show_bug.cgi?id=1181176).

**Comment by joshua-s** [comment]
Assign me please :) Do you have a spec, or can I prototype some designs?

**Comment by gordonbrander** [comment]
@joshua-s we have specs. I'll send them your way.

**Comment by Gozala** [comment]
Ok anyone who wants to help out here are the [wireframes](https://github.com/browserhtml/browserhtml/releases/download/0.15.0/wireframes.pdf) for context menus see page 20.

**Comment by Coder206** [comment]
@Gozala I am interested in working on this.
