### ISSUE TITLE
Default font should not be Fira Sans

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#504]
We should default to Times New Roman (or perhaps Helvetica Neue on Mac)

**Comment by joshua-s** [comment]
This issue seems to have been resolved.

**Comment by gordonbrander** [comment]
Yes, it mostly is, but I caught a few edge cases with inputs and wrote a fix https://github.com/browserhtml/browserhtml/pull/883. Once this PR lands, it will fix this bug.
