### ISSUE TITLE
Create "opened background tab" animation

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#524]
We need an animation to give the user feedback about links opened in the background. I'm thinking a "jump" animation.

**Comment by Gozala** [comment]
@gordonbrander can you provide more details on how it should look, so I can try taking a stab at it ?

**Comment by paulrouget** [comment]
(I'd like to review this once it's done)

**Comment by gordonbrander** [comment]
This should probably be a small icon that appears next to tabs button.

**Comment by Gozala** [comment]
Do we still intend on animating something in a new design ? If so @gordonbrander can you please provide some visuals ?

**Comment by gordonbrander** [comment]
A simple option would be to "light up" the icon when doing `cmd click`. We may also want to "pop" the icon with an animation briefly. This is analogous to the way the File menu highlights when you hit `cmd t`, for example. Here are some first-pass sketches.

![artboard 187 copy 131](https://cloud.githubusercontent.com/assets/58421/12460511/e943c31e-bf68-11e5-8198-6e3d3397290d.png)

A sketch with an animated icon. (Stack pushes down. A new line is pushed into the stack.):

![artboard 187 copy 132](https://cloud.githubusercontent.com/assets/58421/12460535/ff270e7a-bf68-11e5-9b9d-12fc3298589b.png)
