### ISSUE TITLE
Gesture support

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#571]
The synthesis-ui design compliments the visual UI and keyboard shortcuts with trackpad gestures. This is becoming more and more common in many kinds of desktop apps.

We use the following gestures:
- Pinch to zoom out
- 2-finger swipe left/right to go back/forward
- 2-finger swipe up to close tab

The hardware situation:
- All Mac touchpads support up to 9 points of contact and can track touch as well as click.
- New Mac laptops, like the Macbook also support "force touch". These laptops can sense the force of your finger when pushing down. They also introduce a new series of "force touch events" https://developer.apple.com/library/prerelease/mac/documentation/AppleApplications/Conceptual/SafariJSProgTopics/RespondingtoForceTouchEventsfromJavaScript.html. 
- Many windows laptops have touch screens as well as trackpads. In these cases, trackpads may or may not track multiple points of contact.

The software situation:
- Gecko supports touch events https://developer.mozilla.org/en-US/docs/Web/API/Touch
- But we only enable touch events on mobile platforms (Firefox OS and Android)
  - Some websites may abuse feature tests like `'ontouchstart' in document.documentElement` as a way of detecting "mobile" vs "desktop". We should test to see if this is true.

**Comment by gordonbrander** [comment]
Blocks https://github.com/mozilla/browser.html/issues/502.

**Comment by paulrouget** [comment]
I haven't looked, but maybe pointerEvents is the answer.
Also, don't forget we can enable some APIs only for browser.html, not for content.

**Comment by gordonbrander** [comment]
@paulrouget this one? http://www.w3.org/TR/pointerevents/

**Comment by paulrouget** [comment]
Yes.

**Comment by gordonbrander** [comment]
Just for context, Apple apparently isn't implementing pointer events. I don't know if this has put the spec in flux https://daringfireball.net/linked/2015/03/25/google-pointer-events.

**Comment by Gozala** [comment]
I have played with pointer events and it seems that implementation in gecko (at least on desktop) only dispatches events that has `event.pointerType === 'mouse'` which is basically same `mouse(down / move / up)` events that can't be used to implement swipe and flick gestures unless you click the touchpad.

I think at this point it would be best to enable gesture events for browser.html and maybe reimplement them using pointer events once gecko supports `touch` type and we have more time to work out physics.

**Comment by paulrouget** [comment]
2 fingers swipe gestures works in latest graphene.

To use it, see: https://dxr.mozilla.org/mozilla-central/source/dom/interfaces/events/nsIDOMSimpleGestureEvent.idl?offset=100#15

**Comment by Gozala** [comment]
@paulrouget I don't seem to get `MozSwipeGesture` which we need to find out when user released a touch. Could you check is it not fired ? `MozSwipeGestureStart` , `MozSwipeGestureUpdate` and `MozSwipeGestureEnd` do get fired.

**Comment by paulrouget** [comment]
Last time I tried, I don't think I was getting the `MozSwipeGesture` event either.

>  to find out when user released a touch
Can you explain why `MozSwipeGestureEnd` is not enough?

**Comment by Gozala** [comment]
> Last time I tried, I don't think I was getting the MozSwipeGesture event either.
> 
> to find out when user released a touch
> Can you explain why MozSwipeGestureEnd is not enough?

We've covered that during meeting but still commenting here for the record. The issue is that `MozSwipeGestureEnd` is fired at the end of animation (as per comment in the idl and in practice):

> `MozSwipeGestureEnd` - Generated when the swipe animation is completed.

Problem is we need is to react to user releasing a touch, which typically happens earlier than animation is complete (as per comment in idl):

> `MozSwipeGesture` - Generated when the user releases a swipe across across the input device.  This event signals that the actual swipe operation is complete, even though the animation might not be finished yet.

Without `MozSwipeGesture` we can not really tell when user released a touch. And we also can't tell a diff if user swiped up and down or just swiped up and then released, which affects our decision what we do in the UI.

**Comment by Gozala** [comment]
Romeving form the current milestone as it does not really blocks it.

**Comment by gordonbrander** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ORgvAYn2&#x2F;245-gesture-support-571"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Gesture support #571</a>

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open. We would like to implement gestures in Servo but keeping this issue open is not going to help moving that forward.

**Comment by gordonbrander** [comment]
We still want gestures in Servo and we need to track this somewhere. Let's keep this open until this is tracked somewhere else (Servo repo?).

@paulrouget since you're tracking Servo issues, I defer to you.

**Comment by paulrouget** [comment]
Removing P2. This is not going to happen by June.
