### ISSUE TITLE
Make use of flow to get a static type checking for our code base

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#643]
If you have not heard of facebook's [flow](http://flowtype.org/) yet, you should check it out. It adds [algebric data types](https://en.wikipedia.org/wiki/Algebraic_data_type) to JS and provides a a type checker with pretty good type inference.

One of the tradeoffs had being that it slightly alterend JS syntax to add type anotations. Not a long ago support of type [anotations via comments](http://flowtype.org/blog/2015/02/20/Flow-Comments.html) has being added, which means you can write standard JS with some comments and get all the benefits of typechecker.

Now if you think [algebric data types](https://en.wikipedia.org/wiki/Algebraic_data_type) ? What ? We actually already use them for our models and actoins `Record` and friends from `typed-immutable` are poor mans algebric data types with an unfortunate runtime cost.

If we start using flow we could not only catch some of the errors that we currently do at runtime before runnig code but also make our code run faster by romeving all the runtime type checking that is currently in use. 

Unfortunatly there is still few outstanding issues (see facebook/flow#560) to fully support ES6, but once major ones are resolved I'd propose we should  give it a try

**Comment by gordonbrander** [comment]
I'm interested in this, but we should look at this after we get past prototype stage and actually start shipping releases.
