### ISSUE TITLE
Implement webview in Servo

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#651]
Filing bug to track this work. Depends on https://github.com/mozilla/browser.html/issues/639.

**Comment by gedw99** [comment]
Did this even get done ? Or was it the Ted ?

I would like to use servo instead of electron & chrome

**Comment by paulrouget** [comment]
This didn't happen, and won't be happening soon.

**Comment by gedw99** [comment]
Thanks

I found browser.html project from Mozilla which proports to be an Electron
replacement using graphene and servo under the hood.

It also seems from my reading to also be imagined as an embedder engine
type of approach so you could write mobile apps and desktop apps which are
really not webview but you program them with HTML and webassembly.

Am I kind of on the right track here ?

Currently we use google flutter for mobile and electron for desktop, and so
I am prototyping more integrated approaches and with web assembly and servo
being such a game changer I think this could be big.
