### ISSUE TITLE
render monitor

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#664]
Right now tracking performance regressions or even seeing where the bottlenecks are is pretty tedious task and tends to involve a devtools with a debugger etc.. Netflix has build some neat tooling to simplify this task by just by visualizing parts that are re-rendered with a counter showing how many times they are re-rendered: https://github.com/redsunsoft/react-render-visualizer

This task is about integrating it into our toolchain or creating something similar, if integration turns out to be more difficult.

**Comment by Gozala** [comment]
@paulrouget is there any way we could use whatever API is used by paint flashing so we don't have to do some css trickery to do a visualization. I suspect that css trickery will affect overall performance and there for make tool a less effective.

**Comment by paulrouget** [comment]
Paint flashing is only for painting.

For rendering, we did expose events in gecko. They are used in Gaia performance tests. Basically, you define the number of expected reflow. If there's more, the test fail. If there's less, the test fail too (you need to update the test).

The app gets chrome events called `developer-hud-update`, which reflect exactly what the devtools usually send to the frontend. They come with plenty of performance data, including reflow, memory, jank, etc.

To get these events, I think you just need to do this:
```js
navigator.mozSettings.createLock().set({
  'hud.reflows': true,
  'devtools.overlay': true,
  'devtools.overlay.system': true,
});

window.addEventListener('developer-hud-update', …);
```

In Gaia, we built a HUD on top of the app that shows the reflow count, memory, jank, etc. Screenshot: http://paulrouget.com/assets/posts/hud.png

We could do that for browser.html too, pretty easily. We just need to listen to the `developer-hud-update` events.

**Comment by paulrouget** [comment]
We don't know which node is being re-rendered though. Does Netflix actually track rendering or do they use React internals to know that a node has been re-rendered?

Also - this is about rendering. For painting (let's say you change the background color or change some transforms), there's no mechanism to track that other than paint flashing. But I don't think that really matters. Most of the time, if they don't involve a reflow, these are cheap operations.

**Comment by Gozala** [comment]
@paulrouget I think you may have misunderstood my question. What I basically want to do is flush DOM elements that got re-rendered in react sense. This does not necessary mean that any DOM was touched for that element. Originally our main perf bottleneck for performance was related to the fact that change to anything caused calls to almost every view function in the app which generates virtual dom that react diffs and find out there is one attribute to be updated. What I want is to highlight views that were invoked and maybe highlight ones that did not end up updating DOM in distinct way so while running app it will be trivial to spot that we are wasting cycles on obsolete calculations.

The reason I was asking about paint flushing is because I would like to do the highlighting without any DOM mutations to avoid extra overhead that would affect performance. If there is no API to do that I can just overlay semitransparent rectangles over primary DOM to achieve that but I suspect that will slow things down as I'd need to request rects for every view on every run.

**Comment by Gozala** [comment]
> We don't know which node is being re-rendered though. Does Netflix actually track rendering or do they use React internals to know that a node has been re-rendered?

Well react component implement render function (which are our view functions) that's when virtual DOM is computed and returned. My guess is they just instrument these functions to know what has being re-rendered. Please note that re-render does not mean DOM will be touched it just means that virtual-dom is computed and will be then diffed and only if there is any change then actual DOM will be patched.

**Comment by Gozala** [comment]
> Also - this is about rendering. For painting (let's say you change the background color or change some transforms), there's no mechanism to track that other than paint flashing. But I don't think that really matters. Most of the time, if they don't involve a reflow, these are cheap operations.

99% of our time was spend in `React.render(tree, document.body)` which is when react calls all the view functions then diffs to past tree and finally patched DOM. If only few views are invoked in this process then most of the past tree is reused (so no garbage for GC is created) and diff is also super fast as most branches are identical. In the past our issue was related to the fact that many view functions were triggered in this process and 90% of them would return equal but not identical virtual dom nodes, that produced ton of garbage also made diffing process slow as fast identity checks could no longer have being used. Actual DOM updates took tiny fraction of the time. In fact where things were getting out of hand is when sequence of updates would occur in row which is when we caused memory pressure and caused GC to stop the world. What's worst the reason we caused this cascading view calls was because we were computing a "theme" object on every update which was equivalent but not identical that was always different and was passed to almost every view costing us ton of cycles and memory. If we could visualize what is being recalculated during interaction with UI it would be very easy to spot that we're recalculating things that don't need to be.

**Comment by paulrouget** [comment]
Oh, sorry. You're right, I misunderstood what you were saying.

The highlighter API would let you do what you're describing, but it's not exposed to content. We could expose it to the system app maybe, but I think it would be much easier if you could just use a `<canvas>` element (canvas doesn't do any reflow, so the perf impact should be very minimal).

**Comment by Gozala** [comment]
> The highlighter API would let you do what you're describing, but it's not exposed to content. We could expose it to the system app maybe, but I think it would be much easier if you could just use a <canvas> element (canvas doesn't do any reflow, so the perf impact should be very minimal).

I was mostly concerned about calling `.getClientRects` every time. Using canvas instead of overlaying elements as I was gonna go about it sounds a lot better indeed, tanks for suggestion.

**Comment by Gozala** [comment]
I had a prototype of this but as I would like to make it usable with arbitrary dom backends (see #673) I put it on hold until #673 is finished.
