### ISSUE TITLE
Switching animation should not carry on from the current display state.

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#747]
At the moment animations compute every property that is animated from the animation progress. While this greatly simplifies state management overhead for animations it introduces a major limitation - That is:

If say you have `"show-tabs"` animation running (that animates an elements `translateX`) that supposed to have  `d1`ms duration, but after `p1`ms from the start of that animation user triggers `"hide-tabs"` animation (animates `translateX` in an opposite direction) that supposed to run for `d2`ms:

```
show-tabs: -----p1--d1
hide-tabs:      ----------d2
```

You would want to:
1. To animate `x` from the current position which will be different from the generally expected start position.
2. Adjust duration of the `"hide-tabs"` animation presumably so that it will be shorter than `d2` given that starting point of the animated element is different (distance `x` needs to travel shorter).

Initially I assumed that in such case we would generate new animation model `{start, end, time}` but offset it such that `start` progress of the new animation would match up with a progress of the previous animation. But this solution is incomplete given that progress may be translated to `x` with a different  easing in `show-tabs` / `hide-tabs` animation there for `p` progress in `show-tabs` animation may translate to `x` that is different from `y` that is computed from the same `p` progress in `hide-tabs` animation. Not to mention that different animation may animate different properties there for properties not present in the subsequent animation would have to be somehow be transitioned to normal.

In general I think there are following possible solutions:
1. We may just queue action that triggered animation switch until currently running animation is complete.  Possibly speed up the animation.
   
   **Pros:**
   1. Any combination of animations will work without explicit interference.
   
   **Cons:**
   1. UI may appear unresponsive to a user given that interaction will be queued.
   2. Several use actions may end up in a queue while first animation is still completing. In some cases it maybe `show / hide / show` and in such case we either drop first two and require logic to handle this or just go with a queue. In one case UI will appear unresponsive and in other it will appear laggy. 
2. We can store properties being animated into a model instead of computing them in the view. That way switched animation will start from the current state of the model instead of assumed starting point.
   
   **Pros:**
   1. We will switching animations right away and there for UI won't appear laggy or unresponsive.
   
   **Cons:**
   1. Each animation would have to consider all other animations it may be replaced with - meaning that they would have to take into account every property that can be animated and consider how to interpolate it to provide smooth transition (Probably applying some spring physics would make this a lot easier).
   2. Requires extra state management.

**Comment by gordonbrander** [comment]
This also introduces complications with animations that do not have a known fixed time (spring physics for example) If you don't know the fixed time, you can't plot the animation duration.

I think this is still a fairly effective way of grouping fixed-time animations, though.

**Comment by Gozala** [comment]
As I was implementing sidebar animation I realized another shortcoming of the current approach (or used easing library):
https://github.com/Gozala/browser.html/commit/eb1415278280345892112aaa88f20160507fe176

Issue is if we can not really start animation from position other than starting fixed starting point or we need to copy the starting point in order to be able to calculate next position via easing library. Makes me think that using spring physics would be a better solution as that way we can reversing animation from any point and have no need to copy that state or do extra calculations to figure out new animation duration.

**Comment by Gozala** [comment]
@gordonbrander when do you thing would be a good time for me to work on this ?

**Comment by Gozala** [comment]
Pasting some relevant discussion that happened on Slack

> gordonb [4:00 PM] 
> @gozala: regarding fixed-time animations... I think the minimum information we need is:

> ​[4:00] 
> 1. Progress

> ​[4:00] 
> 2. Direction (fwd/backward)

> ​[4:00] 
> 3. Current value

> ​[4:01] 
> 3. start value

> ​[4:01] 
> 4. end value

> ​[4:01] 
> I believe these are the values that `@keyframes` tracks

> gozala [4:03 PM] 
> @gordonb: what is direction ?

> gordonb [4:03 PM] 
> whether progress is toward `start` or `end`

> ​[4:03] 
> this lets you do reversible animations

> gozala [4:04 PM] 
> @gordonb: well why not just swap stard and end in that case ?

> gordonb [4:04 PM] 
> sure. I'm suggesting to keep start and end as constants, but either way works.

> ​[4:04] 
> that way you don't need `begin` for example

> gozala [4:05 PM] 
> @gordonb: Yeah I was thinking about something along those lines

> ​[4:05] 
> to have something like `Transition.init(start, end, duration)`

> gordonb [4:06 PM] 
> yeah

> ​[4:06] 
> it may also be worth considering multiple keyframes

> gozala [4:06 PM] 
> then on ticks it will update current

> gordonb [4:06 PM] 
> e.g. minimum definition is 0% and 100% but can have keyframes at 44%, etc

> ​[4:06] 
> and automatically tween between those points

> gozala [4:13 PM] 
> @gordonb: ok how about this then

> ​[4:15] 
> ```
const slideIn = transition([ [0, { y: -200}], [100, {y: 200}] ])
Transition.init(slideIn, 200)
```
> (edited)

> ​[4:18] 
> where API is:

> ```
type Percent = number
type Keyframe <display> = [Percent, display]
type Keyframes <display> = Array<Keyframe<display>>
>
type Model<display> =
  { state: display
  , keyframes: Keyframes<display>
  , elapsedTime: Time
  , duration: Time
  }
>
type Action
  = {type: "Tick", time: Time}
  | {type: "End"}
>
>
type init <display> = (current:display, keyframes: Keyframes<display>, duration) =>
  [Model<display>, Effects<Action>]
>
type update <display> = (Easing, Interpolation<display>) => (model:Model<display>, action:Action) =>
  [Model<display>, Effects<Action>]
```
> (edited)

> gozala [4:30 PM] 
> @gordonb: I’m not entirely sure how to apply easing to all this bet I can figure it out(edited)

> ​[4:33] 
> @gordonb: Like I imagine you may want to use different easing between keyframes

> ​[4:35] 
> @gordonb: alternative that works today is to just chain transitions

> ​[4:35] 
> meaning translate keyframe position to ms

> ​[4:36] 
> and have SlideIn FadeIn etc...

> ​[4:36] 
> start one after another

> ​[4:36] 
> although I guess reversing that will be tricky :disappointed:

> gordonb [4:49 PM] 
> @gozala: it may be better to apply easing to progress rather than keyframes

> ​[4:49] 
> This is what @keyframes does

> ​[4:50] 
> So ease progress and then apply to entire animation to get display values

> gozala [4:52 PM] 
> Oh right I guess we could make `Transition.update` be configurable

> ​[4:54] 
> like `Transition.update = (easing, update, duration) => (model, action) => [model, Effects<Action>]`

> ​[4:55] 
> let me actually update type signature I initially wote

> ​[4:57] 
> @gordonb: see above where `Interpolation` and `Easing` are: https://github.com/Gozala/eased/blob/master/type/index.js#L10-L13

​> [5:02] 
> @gordonb: in fact I just realized that it’s probably won’t be too hard to add keyframes support to eased libarary

> ​[5:04] 
> @gordonb: in fact it will be super easy I think

> ​[5:04] 
> so currently it looks like this

> ​[5:04] 
> https://github.com/Gozala/eased/blob/master/src/index.js#L10-L11

> ​[5:04] 
> so you basically have just 0 and 100 keyframes

> ​[5:05] 
> all you would have to do is change that to passing `…keyframes` instead of `from` and `to`

> ​[5:06] 
> and then given a progress decide between which two keyframes your progress falls and pass that to interpolation instead

> ​[5:06] 
> that’s it

> ​[5:08] 
> @gordonb: although I guess in css you can omit some fields in keyframes and then css will expand their timeline

> ​[5:09] 
> ok so little tricker than I thought but should be still simple enough

> ​[5:10] 
> the only tricky part is how to figure out what needs to fall through if you can’t tell what are you interpolating
