### ISSUE TITLE
Draggable area of window should be size of title bar

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#767]
Currently too much of the window is draggable. For example in tabs view, the entire background area is draggable. We should restrict dragging to the toolbar area.

**Comment by Gozala** [comment]
I thought it was a feature :)

**Comment by gordonbrander** [comment]
In the current version, dragging also sometimes doesn't work. The behavior is inconsistent.

**Comment by fgimenez** [comment]
Hi, I would like to work on this issue, could you please assign it to me and give me some details about how to begin with it?

Thanks! :)

**Comment by paulrouget** [comment]
This is actually not an issue anymore. The way it works in Servo is different from what we had in Gecko.

@gordonbrander can you confirm?

**Comment by gordonbrander** [comment]
Yup, true!
