### ISSUE TITLE
Hide and show webviews without z-index

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#788]
`z-index` should not be used when hiding/showing webviews (https://github.com/mozilla/browser.html/blob/master/src/browser/web-view.js#L293-L300). It causes stacking issues in Gecko and Servo. We should use `pointer-events: none` and `opacity` or `visibility` instead (https://github.com/paulrouget/perseptive-skeleton/blob/master/main.css#L72).

**Comment by gordonbrander** [comment]
Aha! The z-index change was introduced for the cross-fading-between-tabs animation to work properly.

**Comment by gordonbrander** [comment]
@paulrouget do we have z-index in Servo now?

**Comment by paulrouget** [comment]
z-index should work. If it doesn't, please let me know.

**Comment by Gozala** [comment]
This no longer seems relevant.
