### ISSUE TITLE
Create full-screen window control sprite

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#796]
From https://github.com/mozilla/browser.html/pull/795#issuecomment-169421862

> BTW I found few issues with our code when I was doing this work. There is one I'd need your help to resolve it - When we enter the full screen mode toggle (green) button should have a different image when hovered. Would be really cool if you could add it to the current button window-controls.sprite.png.

@paulrouget do we plan on doing window controls in HTML or with native code? Will this be different between Gecko and Servo?

**Comment by paulrouget** [comment]
For Gecko, we can choose between HTML or native. For Servo, it's only native for now.

**Comment by gordonbrander** [comment]
Maybe we should do native for both? @paulrouget is this hard to do in Gecko? Is it a switch we can flip?

**Comment by paulrouget** [comment]
Not too hard. I can look at this tomorrow.

**Comment by paulrouget** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1237500

**Comment by Gozala** [comment]
What is the benefit of using native controls on gecko ? Presumably we want non-native ones in servo as well so I don't think there is real benefit to using native controls in gecko (sorry @paulrouget for commenting after you already wrote a patch).

What would be helpful though is to have a way of telling if we can use custom controls or not so we can adjust code base accordingly.

**Comment by gordonbrander** [comment]
The goal is to reduce the difference between Gecko and Servo. Since adding window control APIs to Servo is work and the payoff is small I think we should go with native controls for now. Not to say we can't build window control APIs into Servo later, just that other areas of Servo work are higher priority atm.

**Comment by Gozala** [comment]
@gordonbrander I'm not arguing with that, I just think that leaving gecko as is, is a better option. As we already have a working code that handles each state. In servo our controls are just overlaid with native ones (until we get to fix that).
