### ISSUE TITLE
Animate close button on tabs

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#802]
Follow up for https://github.com/mozilla/browser.html/issues/789.

**Comment by joshua-s** [comment]
What should this animation look like?

**Comment by joshua-s** [comment]
What should this animation look like?

**Comment by gordonbrander** [comment]
@joshua-s an example can be found in this prototype https://github.com/gordonbrander/browser.html-prototypes/tree/master/01

Previously Servo didn't support CSS transitions, which means using our built-in animation engine instead. I'm not sure if this is still the case. cc @paulrouget.

**Comment by paulrouget** [comment]
Transitions work.

**Comment by gordonbrander** [comment]
Ok, implementing with CSS transitions will probably be simplest.

**Comment by joshua-s** [comment]
You can assign me :)
