### ISSUE TITLE
Opening urls from other apps in browser.html is broken

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#818]
This currently relates to following issues:
1. [x] Our window open handler is regressed at some point.
2. [ ] OSX does not like application that contain `.` in them.

**Comment by Gozala** [comment]
For the second issue we need to rename application to remove `.` character. @paulrouget @gordonbrander let's discuss that tomorrow.

**Comment by gordonbrander** [comment]
@Gozala what was the outcome of our discussion?
