### ISSUE TITLE
Servo doesn't support mozSettings API

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#833]
@Gozala @paulrouget do you know if there is any way to shim this or work around?

<img width="682" alt="screen shot 2016-01-15 at 16 28 02" src="https://cloud.githubusercontent.com/assets/58421/12368886/078b1e84-bba5-11e5-87fa-65375a4ecd96.png">

**Comment by paulrouget** [comment]
Why do we use the settings again? To configure some debug/devtools options, right? I don't think we want to go this route servo. We will eventually get a runtime, which will have an Electron-like API to configure these debug/devtools options (so nothing at the window level).

So we probably just want to bail when there's no settings api.
