### ISSUE TITLE
Implement swipe-to-go-back

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#842]
Depends on https://github.com/mozilla/browser.html/issues/571.

Here's a comp showing a page mid-swipe.

![artboard 187 copy 125](https://cloud.githubusercontent.com/assets/58421/12433309/4a1fbbf2-beb5-11e5-845b-a6de13970983.png)

**Comment by gordonbrander** [comment]
Here is an alternate (preferred) visual treatment that also animates z-axis.

![artboard 187 copy 126](https://cloud.githubusercontent.com/assets/58421/12433400/b5998ee4-beb5-11e5-8216-46a9ced9a7e5.png)

**Comment by paulrouget** [comment]
Can you describe more precisely the back/forward gesture and animations?

**Comment by gordonbrander** [comment]
Here's what we would like to do:

- 2f Swipe from left to right
- Page animation is driven by finger movement. You can think of animation as being on a "track" and the distance your finger travels from left to right is correlated with the progress of the animation.
- You must drag past a threshold to go back. Once you release past a threshold, the animation completes. The animation integrates velocity from swipe.

Previously, when we explored this, we decided that the ideal would be to expose a TouchEvent-like API for trackpads. That would make it easy to implement something like this.

If it's too hard, I can defer this bug and open one for a short-term design that shows a back arrow when you swipe.

**Comment by Gozala** [comment]
Here is the previous issue on file #502 and an implementation that was in place #650 before we removed this feature due to lack of gesture support in servo.
