### ISSUE TITLE
Bring back "new tab"

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#843]
Our first pass could be to bring back the website tiles. I love these from the standpoint of usability. It's really easy to recognize your favorite sites this way.

![artboard 187 copy 114](https://cloud.githubusercontent.com/assets/58421/12433654/2b717112-beb7-11e5-86e9-2d91e747e0f9.png)

**Comment by paulrouget** [comment]
Yes!

**Comment by matthewp** [comment]
This is really nice.

**Comment by Gozala** [comment]
Depends on #843

**Comment by Gozala** [comment]
Fixed by #1047
