### ISSUE TITLE
Search suggestions are forced, blowing away what you type

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#869]
There's a bug with the current search implementation that blows away what you type, replacing it with the current search suggestion. This means you can't actually type what you want if it doesn't match the first suggestion.

Screen recording: https://drive.google.com/file/d/0B1az_KF0ZYc_aGh1cHdwVVZoTHc/view?usp=sharing

cc @Gozala

**Comment by Gozala** [comment]
@gordonbrander Interesting, I did not realized that we would get suggestions where we don't have a match so I never considered that case :( Thinking about this I'm also not sure what is it we can do in such case. I see following options:

1. Throw away suggestions that don't contain typed query in the beginning of the suggestion.
2. Display what you typed and display suggestion title as  a hint (like we're going to do for history suggestions).

I also noticed that in some cases typed message does not always match beginning which is another problem as we can't have two selections. So we need solution for this as well. I see following options:

1. Throw away such matches.
2. Throw away text before the query.
3. Just display what you typed and show title as hint.
4. Change a UX so we don't use selections but rather something more similar to what was in original mocks. That way we could pretend that text before and after the match is selected.

**Comment by gordonbrander** [comment]
@Gozala

We don't necessarily need to throw away suggestions whose match doesn't match the text, but they shouldn't replace the text.

3 sounds like a good option.

Another good option would be to keep these suggestions, but demote them so they are never used as auto-completions.

**Comment by Gozala** [comment]
In fact there is another problem with the way we implement suggestions right now:

Try going to `medium.com` by typing `medium.` presumably you'll get following picture:

<img width="509" alt="screen shot 2016-02-16 at 5 29 04 pm" src="https://cloud.githubusercontent.com/assets/21236/13097043/de3a2c54-d4d2-11e5-8fdf-399029d298de.png">

So you can't really type `medium.com` but even if you typed really quick and managed to do so, or if we implemented what we've discussed above. You'd still wind up with `medium.com` in the address bar and suggestion hint for something whatever else (in the hint view). But pressing enter will take end up taking you to a imperfect place, which is at best `duckduckgo.com?q=medium.com`.

@gordonbrander To resolve this I think we need to do more stuff. Like:

1. If suggestions don't start with what you typed do not select any suggestion at all. That way pressing enter will not suddenly load suggestion that doesn't really match yours.
2. If moved selection across suggestions but continued typing reset selection.

Still what if you typed something like `medium.com` and you got suggestion that matches it then we select it but you likely did meant to go to `medium.com` and not search for it. This is going to get better as we'll implement history suggestions, but still I feel like we need to handle case with no `TopHit` match more explicitly.

**Comment by gordonbrander** [comment]
> If suggestions don't start with what you typed do not select any suggestion at all. That way pressing enter will not suddenly load suggestion that doesn't really match yours.

Yes, agreed. I'm adding this to the spec.
