### ISSUE TITLE
Integrate force touch for switching to show-tabs mode

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#872]
Wireframe forthcoming.

**Comment by paulrouget** [comment]
For the record, there are 4 phases:

1. touchpad at rest (`force = 0`)
2. pressure on the touchpad, first click not reached (`0 < force < 1`)
3. pressure on the touchpad, first click reached, second click not reached (force: ``1 < force < 2``)
4. pressure on the touchpad, second click reached (force: `2 < force < 3`)

Clicking happens when `force = 1` and `force = 2`.

**Comment by paulrouget** [comment]
Here is a quick-and-dirty hack that shows how it can be done:

```js
var THRESHOLD = 1.5;
var MAX = 2.5;

window.addEventListener("load", () => {
  var stack = document.querySelector(".webviews-stack");
  var overlay = document.querySelector(".overlay");
  var sidebar = document.querySelector(".sidebar");

  function update(t) {
    stack.style.transform = `translate3d(0px, 0px, ${-200 * t}px)`;
    overlay.style.opacity = 0.1 * t;
    sidebar.style.transform = `translateX(${(1 - t) * 550}px)`;
  }

  document.documentElement.addEventListener("webkitmouseforcechanged", e => {
    var force = e.webkitForce;
    if (force >= THRESHOLD && force <= MAX) {
      update((force - THRESHOLD) / (MAX - THRESHOLD));
    } else if (force < THRESHOLD) {
      update(0);
    }
  });
  document.documentElement.addEventListener("mouseup", e => {
    update(0);
  });
});
```

**Comment by paulrouget** [comment]
demo: https://streamable.com/5j47

**Comment by paulrouget** [comment]
I'm working a proper PR for Servo. I do not use the `webkit` prefix anymore, but `servo`.

**Comment by paulrouget** [comment]
Any update?

**Comment by gordonbrander** [comment]
Working on it now :)

**Comment by gordonbrander** [comment]
Note to self: use `--pref dom.forcetouch.enabled` to toggle force touch on in Servo.
