### ISSUE TITLE
The pin button is clicked 4 times with Servo

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#876]
This used to work.

I'm not sure why, but the pin button behaves as if it was clicked 4 times with Servo.

![b](https://cloud.githubusercontent.com/assets/373579/13139524/4c2930ba-d62d-11e5-8e47-ca73a7e9719b.gif)

See the double bounce? It's like the sidebar shows up, then hides, then shows up and hides again.

I don't know where the JS click event handler is.

@Gozala can you help?

**Comment by Gozala** [comment]
@paulrouget ok here is an overview how things are wired there:

1. Sidebar's bottom part contains a sidebar/toolbar containing pin toggle button:
https://github.com/browserhtml/browser.html/blob/master/src/browser/sidebar/toolbar.js#L156
2. Events / Actions from pin button are mapped via `ToggleAction` function:
https://github.com/browserhtml/browser.html/blob/master/src/browser/sidebar/toolbar.js#L29-L35
Idea there is to recognize "Check" and "Uncheck" actions and handle them at the toolbar level while delegating all other actions to the button itself:
https://github.com/browserhtml/browser.html/blob/master/src/browser/sidebar/toolbar.js#L78-L84
3. Sidebar itself does a similar thing by recognizing `Attach` / `Detach` type actions:
https://github.com/browserhtml/browser.html/blob/master/src/browser/sidebar.js#L89-L92
4. And so does it's parent `Browser`:
https://github.com/browserhtml/browser.html/blob/master/src/browser/browser.js#L93-L96
5. When those actions occur, Browser triggers following batched updates
https://github.com/browserhtml/browser.html/blob/master/src/browser/browser.js#L575-L591
6. WebView movement is triggered by `Shrink` / `Expand` actions from above updates:
https://github.com/browserhtml/browser.html/blob/master/src/browser/browser.js#L724-L728
7. Which in turn causes call to [`shrink`](https://github.com/browserhtml/browser.html/blob/master/src/browser/browser.js#L616-L620) and more interestingly to [`startResizeAnimation`](https://github.com/browserhtml/browser.html/blob/master/src/browser/browser.js#L623-L627)
8. On each tick `ResizeAnimationAction` will be send into update loop and there for trigger [`updateResizeAnimation `](https://github.com/browserhtml/browser.html/blob/master/src/browser/browser.js#L639-L688) that just updates `model.browser.display.rightOffset` until animation elapses duration.
9. On the view side width of the div containing most browser UI is calculated from above mentioned `rightOffset`.

Give that I don't see bounce in Gecko my guess would be is that it's either:

1. Somehow events from toggle button are invoked more than once causing multiple actions. The way toggle button works is:
  1. [`onclick` it sends a `Press` action](https://github.com/browserhtml/browser.html/blob/master/src/common/toggle.js#L136)
  2. On `Press` model's [`isChecked` flag is flipped](https://github.com/browserhtml/browser.html/blob/master/src/common/toggle.js#L74) and [`Check` or `Uncheck` action is send back depending on the `isChecked` state](https://github.com/browserhtml/browser.html/blob/master/src/common/toggle.js#L75-L78)

  As a first thing I'd make sure that clicking a pin button causes only one `Press` and then only one `Check` or `Uncheck` in return. 

2. If only one `Check` action is triggered, than likely issue is with an animation itself. So it should be related to above mentioned [`updateResizeAnimation `](https://github.com/browserhtml/browser.html/blob/master/src/browser/browser.js#L639-L688) function. It's either at the end of it we somehow restart the loop or maybe math is wrong there, although that would make it difficult to explain behavior diff with gecko.

**Comment by paulrouget** [comment]
onClick is called twice. Servo bug.

**Comment by paulrouget** [comment]
https://github.com/servo/servo/issues/9702

**Comment by paulrouget** [comment]
Fixed by https://github.com/servo/servo/commit/875f1e92ccafebc8ddebc722f430e5037007b9dc
