### ISSUE TITLE
Update the progressbar behavior with mozbrowserconnected

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#882]
Until now, a page was either loading or loaded. Now it can also be in a "connecting" mode.

The 3 events that matter are: `mozbrowserloadstart`, followed by `mozbrowserconnected`, and finally `mozbrowserloadend`. So the page can be in 3 states: *connecting*, *loading*, *connected*.

What I would suggest this behavior:

Here is how I would build it: http://jsbin.com/kucubiyixe/1/edit?html,js,output - I hope the comments help.

**Comment by gordonbrander** [comment]
Related: https://github.com/browserhtml/browserhtml/issues/839
