### ISSUE TITLE
tab switch should not animate if ctrl is realized quickly

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#905]
Tab switching via `ctrl-tab` / `ctrl-alt-tab` should switch tabs without animation if ctrl is realized quickly.

**Comment by Gozala** [comment]
@gordonbrander Do you have anything to add to this ?

**Comment by paulrouget** [comment]
@gordonbrander ping?

**Comment by gordonbrander** [comment]
@Gozala and I talked about this in detail. Assigning him.

**Comment by Gozala** [comment]
I'll deal with this after #963
