### ISSUE TITLE
Make it look good on Linux

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#913]
Not sure yet what we want to do here, but browserhtml needs to work correctly on Linux.

**Comment by Anachron** [comment]
I have ArchLinux at home, so I could be testing and debugging.

**Comment by paulrouget** [comment]
I think there are 2 things we can do:

Option 1, figure out a way to make a border-less draggable and resizable window on Linux. I guess that's only possible if we use a widget toolkit, or if we use wayland (which is supported),

Option 2,  we just rely on the window manager to draw the window decoration (as it is now), but then we need to hide the window controls (osx buttons for now).

I would go for (2) first.

This means browser.html needs to know if decorations/titlebar surround the servo window. And I would suggest to do this: https://github.com/browserhtml/browserhtml/issues/915

**Comment by Anachron** [comment]
I'd go for 2 as well. I have 3 different wms for testing 1 though. 

I'd not recommend Wayland yet. Even though its testable, it still segfaults for me. 

When will you get to check #915?

**Comment by paulrouget** [comment]
> When will you get to check #915?

Not anytime soon.

I do have a Linux box here. The only thing that stands out is the titlebar.

**Comment by paulrouget** [comment]
I'm about to fix #915. @gordonbrander Is there anything we want to do here?

**Comment by gordonbrander** [comment]
@paulrouget we will not hide the title bar on Linux, correct?

**Comment by paulrouget** [comment]
> @paulrouget we will not hide the title bar on Linux, correct?

titlebar will be native.

**Comment by paulrouget** [comment]
I consider this done.
