### ISSUE TITLE
Add window controls only if titlebar-less window

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#915]
We need window controls only on Mac, when the `-b` option is passed.

I suggest that we pass options to the document via the hash to tell browerhtml if it should use window controls or not.

For example: `index.html#titlebar=true`

**Comment by paulrouget** [comment]
@gordonbrander / @Gozala can one of you look at this?

**Comment by paulrouget** [comment]
I'll take care of it.

**Comment by paulrouget** [comment]
A easier solution is probably to just use `navigator.platform` and just assume no native titlebar on mac.

**Comment by gordonbrander** [comment]
@paulrouget why not use `browserhtml.json` config file? We could allow `.mach` to choose a config file, for example.

**Comment by paulrouget** [comment]
> @paulrouget why not use browserhtml.json config file? We could allow .mach/ to specify a config file, for example.

So when we package Servo, we would put a `os:…` in `browserhtml.json`?
That won't help. Instead of querying the OS, we would query the json file.

We need a way for the runtime, at *runtime*, to tell if a native titlebar is used or not. This will happen once we get the proper Electron-like runtime.

**Comment by gordonbrander** [comment]
@paulrouget we're creating different app packages for the different OS's. This means we can have different config files for these different app packages. Seems like a simple fix, but I'm not married to it. I'm open to whatever solution makes sense.
