### ISSUE TITLE
Experiment with showing multiple iframes when sidebar is displayed

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#918]
… the 3D view thingy with stacked iframe

**Comment by paulrouget** [comment]
How much work is that? Can someone describe what needs to be done here?

**Comment by paulrouget** [comment]
Do we have wireframes for that?

**Comment by gordonbrander** [comment]
I've added a wireframe for this, along with interaction notes. https://drive.google.com/file/d/0B1az_KF0ZYc_bzIyZzJRTm4tZVk/view?usp=sharing. We also have these interactive prototypes that show how the interactions work https://github.com/gordonbrander/browser.html-prototypes.
