### ISSUE TITLE
Make browserhtml looks less webby and more part of the OS

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#919]
Gordon knows what that means.

**Comment by paulrouget** [comment]
We need an visual update on:
* dashboard
* sidebar
* titlebar

**Comment by gordonbrander** [comment]
We need to fix subpixel antialiasing on fonts in Servo. I thought there was a bug for this, but I'm having trouble finding it.

**Comment by gordonbrander** [comment]
Blocked by subpixel antialiasing in Servo. Filed a bug with Servo https://github.com/servo/servo/issues/10199.

**Comment by Coder206** [comment]
@paulrouget @gordonbrander I was thinking, it might be more intuitive to the user if we can use the default OS font. With code like this: https://css-tricks.com/os-specific-fonts-css/

**Comment by paulrouget** [comment]
As for today, we use os fonts. So not problem here.

**Comment by magsout** [comment]
@Coder206 @paulrouget or maybe with this code https://medium.com/designing-medium/system-shock-6b1dc6d6596f#.jbj9ksypi ?

**Comment by paulrouget** [comment]
There is no CSS problem here.
