### ISSUE TITLE
Make it look good on Windows

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#925]
Not sure yet what we want to do here, but browserhtml needs to work correctly on Windows.

**Comment by paulrouget** [comment]
This [comment](https://github.com/browserhtml/browserhtml/issues/913#issuecomment-197912816) applies here as well.

**Comment by paulrouget** [comment]
I'm about to fix #915. @gordonbrander Is there anything we want to do here?

**Comment by gordonbrander** [comment]
Do we hide the title bar on windows?

**Comment by paulrouget** [comment]
> @paulrouget do we hide the title bar on windows?

titlebar will be native.

**Comment by paulrouget** [comment]
I consider this done.
