### ISSUE TITLE
Some gradients appear in web pages

### ISSUE THREAD

**Issue by laurentj** [browserhtml/browserhtml#929]
When I open http://slimerjs.org with browserhtml  `./mach run --browserhtml`, some gradients appear on some html elements.

![servo_box_gradient](https://cloud.githubusercontent.com/assets/336034/13776971/68ed87d4-eaad-11e5-87f8-6137d4fcde74.png)

If I open the web site directly with Servo `./mach run http://slimerjs.org` (or when I open it in Firefox), there are not these issues.

Servo build: commit 075ce98 , release build, on linux Kubuntu 15.04 64bits

**Comment by paulrouget** [comment]
Hmm… most likely a webrender issue. I think we have a similar issue with http://firefox.com and the green button.

**Comment by paulrouget** [comment]
I'll try to build a simple test case and file an issue.

**Comment by paulrouget** [comment]
Note: might be related to https://github.com/servo/servo/issues/10115#issuecomment-200057660

**Comment by paulrouget** [comment]
With latest webrender version, this is fixed.
