### ISSUE TITLE
Need to type backspace twice to delete a character in the url bar

### ISSUE THREAD

**Issue by laurentj** [browserhtml/browserhtml#930]
To delete one character in the url bar, with the backspace key, I need to type two times on this key. 

Servo build: commit 075ce98 , release build, on linux Kubuntu 15.04 64bits, azerty keyboard.

**Comment by paulrouget** [comment]
Can reproduce on Mac, Qwerty. It appears to be browserhtml specific.

**Comment by paulrouget** [comment]
Might be related to the recent implementation of `setSelectionRange`.

**Comment by paulrouget** [comment]
Can someone investigate and see if it's a Servo bug or a bhtml bug?

**Comment by laurentj** [comment]
Well the bug appears only in the url bar of bhtml. Not in any other input field of web pages.

**Comment by paulrouget** [comment]
But we don't have the issue with Gecko. Might be an issue with key events + `setSelectionRange`.

**Comment by mbrubeck** [comment]
This is a Servo bug: servo/servo#10182.

**Comment by paulrouget** [comment]
Works now.
