### ISSUE TITLE
SVG UI icons?

### ISSUE THREAD

**Issue by tigt** [browserhtml/browserhtml#932]
I'd like to contribute in the one way I feel confident doing: making SVG versions of the existing bitmap UI elements. But I wanted to check if that was a good idea:
- How is Servo at SVG? It's [supposed to be capable of basic SVGs](https://github.com/servo/servo/pull/4623), but I'm sure there are known bugs that I couldn't google.
- Bad perf impact? Current browsers are far faster at decoding/resizing/painting bitmaps than parsing/building/rendering/rasterizing/painting SVG, but I dunno how relevant that is here.

The proposed benefits would be more flexible styling, theming, and `@media` responsiveness, and future-friendliness towards the myriad of viewports, densities, and zoom levels.

**Comment by paulrouget** [comment]
Servo doesn't support SVG yet :/

This bug is about canvas.
