### ISSUE TITLE
OSX - Alternative keymaps not working

### ISSUE THREAD

**Issue by pzuraq** [browserhtml/browserhtml#933]
Super excited about this project, it's coming along much faster than I thought it would :smile: 

I downloaded and compiled to try it out, and found that the keymaps I had on my computer weren't working. I use dvorak, but when I typed it came out as qwerty. I'm using the standard system language chooser.

**Comment by paulrouget** [comment]
Thanks for trying!

Keymap issue is tracked here: https://github.com/servo/servo/issues/4144
