### ISSUE TITLE
The overscroll background color doesn't mach the titlebar color

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#934]
<img width="707" alt="screen shot 2016-03-16 at 09 40 10" src="https://cloud.githubusercontent.com/assets/373579/13806309/21ca95d2-eb5b-11e5-96e1-73deff812558.png">

**Comment by paulrouget** [comment]
Can someone investigate and see where the background color come from? Is it the iframe background or the deepest layer of the page?

**Comment by paulrouget** [comment]
@gordonbrander ^

**Comment by gordonbrander** [comment]
@paulrouget the title bar color comes from the `theme-color`, but can be overrided via a list of hardcoded colors.

Maybe what we actually need is a way to get the background color of the deepest layer in the page and use that everywhere.

**Comment by paulrouget** [comment]
I'm looking for the color of the overscrolled region. The white part in the screenshot. Why is it white?
Once we know that, then we know where to apply the `theme-color`.

**Comment by gordonbrander** [comment]
I thought Servo's overscroll extended the background color of the page, but now I'm suspecting it's always just white.

If I `./mach run -r -w http://everytimezone.com/` (which has a dark background color on the body element), I still get white overscroll.

<img width="912" alt="screen shot 2016-03-21 at 15 18 20" src="https://cloud.githubusercontent.com/assets/58421/13936057/4b7a71f6-ef78-11e5-86e4-91d56381d09c.png">

**Comment by paulrouget** [comment]
The white color must come from somewhere

**Comment by paulrouget** [comment]
It's the background of the iframe (white by default). See https://github.com/browserhtml/browserhtml/pull/947
