### ISSUE TITLE
can't publish a new version of bhtml:  'color-structure' is not in the npm registry

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#939]
See: https://travis-ci.org/browserhtml/browserhtml/builds/117384339

**Comment by paulrouget** [comment]
@gordonbrander or @Gozala can someone take a look at this?

**Comment by gordonbrander** [comment]
Looks like the name of the dependency changed https://github.com/Gozala/eased/blob/master/package.json. Assigning @Gozala.

**Comment by paulrouget** [comment]
so it's just a mater of updating ease?

**Comment by Gozala** [comment]
@paulrouget Yes. Also I'm on it, updating bunch of other deps as well.
