### ISSUE TITLE
"open in new tab" feature

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#940]
This requires Servo support. Relevant bug is here: https://github.com/servo/servo/issues/10099

But we also need browserhtml support:
- support the `mozbroweropentab` event (i think this is already the case)
- do something in the UI to make it clear that a background tab has been opened

**Comment by gordonbrander** [comment]
Here's a video that shows the animation we want to have for "open-in-new-tab" https://drive.google.com/file/d/0B1az_KF0ZYc_WlFxUmhhMFJZQmc/view?usp=sharing.

Rational: new tabs are appended to the top of the sidebar. The motion design literally has the page appear from the top and slide over the previous tab, informing the user of what happened.

**Comment by Gozala** [comment]
@gordonbrander looks really cool, although in reality with loading page it's likely going to look worse :( Anyway what's supposed to happen if you sidebar is pinned ?

**Comment by gordonbrander** [comment]
@Gozala I didn't include loading sequence in AE animation because due to time constraints, but should be fine. It will animate in as white page.

If sidebar is pinned, no change. The sidebar will remain stationary to the right of the WebView area.

**Comment by Gozala** [comment]
> If sidebar is pinned, no change. The sidebar will remain stationary to the right of the WebView area.

I mean we need to add tab into sidebar, presumably animate that somehow as well no ?

**Comment by gordonbrander** [comment]
@Gozala that's true! It should slide down other tabs, fade in.

**Comment by gordonbrander** [comment]
@Gozala but to start, we can just make it appear immediately.

**Comment by paulrouget** [comment]
P1 -> P2
