### ISSUE TITLE
Only show the back button if we can go back

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#941]
Or maybe grey it out? @gordonbrander what do you think?

`getCanGoBack` is not implemented in Servo, but I'd like to implement it differently. Maybe instead of implementing a specific method, we could just add a `canGoBack` / `canGoForward` property to the `mozbrowserlocationchange` event. @Gozala what do you think?

**Comment by paulrouget** [comment]
Browser API change: https://github.com/servo/servo/pull/10100

**Comment by gordonbrander** [comment]
:+1: My strong inclination is to only show it if you can go back, but I think "greying it out" or making it very transparent is a reasonable approach as well.

**Comment by paulrouget** [comment]
> My strong inclination is to only show it if you can go back

I'm ok with that.

**Comment by paulrouget** [comment]
I've implemented canGoBack / canGoForward in Servo. I've updated the MDN documentation: https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowserlocationchange

It hasn't landed yet. But it's been r+'ed.

**Comment by paulrouget** [comment]
Landed: https://github.com/servo/servo/commit/6577409b95bc782c0493cc5186fa4ed0d31d680d

**Comment by paulrouget** [comment]
New Servo build include this change.

Can someone look at this?
