### ISSUE TITLE
loading indicator not clipped

### ISSUE THREAD

**Issue by Swatinem** [browserhtml/browserhtml#953]
When opening the tab view when the loading indicator is still visible, you can clearly see that it is not clipped to page bounds

![bildschirmfoto von 2016-03-23 11-27-21](https://cloud.githubusercontent.com/assets/580492/13982463/8fba3dec-f0ea-11e5-824a-613898d7f4a1.png)

**Comment by paulrouget** [comment]
Servo issue. Overflow issue. We'll need a reduced test case.

**Comment by paulrouget** [comment]
Reduced. Filed: https://github.com/servo/servo/issues/10164

**Comment by paulrouget** [comment]
This works now with latest WR. Closing.
