### ISSUE TITLE
Pressing escape when the content has focus quit the app

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#972]

**Comment by tschneidereit** [comment]
Focus needs to be on a text input for this to reproduce.

**Comment by paulrouget** [comment]
https://github.com/servo/servo/issues/11194

**Comment by paulrouget** [comment]
PR on its way: https://github.com/servo/servo/pull/11200

This will require to start Servo with this option: `--pref shell.quit-on-escape.enabled=false`
