### ISSUE TITLE
Use a fallback favicon, the same way Safari does

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#973]
Go to example.com. There's no favicon defined. Now, pin example.com in Safari. They build a favicon based on the first letter of the title.

**Comment by Gozala** [comment]
That seems neat, I like the idea.

**Comment by Coder206** [comment]
@paulrouget Did you have a chance to try Test Pilot for FireFox yet? I think there may already be "in-house" code we could use to implement this great idea.

**Comment by Coder206** [comment]
@paulrouget I found a code script in JS by Mozilla Activity Stream. This may help us implement this: https://github.com/mozilla/activity-stream/blob/master/content-src/components/SiteIcon/SiteIcon.js

**Comment by paulrouget** [comment]
@Coder206 cool! Maybe this is something we should reuse.

**Comment by Gozala** [comment]
@paulrouget It would be nice if we could extract site colors so we could use a major color as background for the icon.

**Comment by Coder206** [comment]
@Gozala I like the idea of a personalized icon! I think it's important to make sure the foreground of the icon has a different colour (to avoid an icon of one colour - no contrast)

**Comment by Coder206** [comment]
Of course, it would be an unlikely scenario for a well designed website (colour wise)
