### ISSUE TITLE
When 2 tabs are open, CPU around 45% (infinite rAF loop)

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#976]
With only one tab, CPU is very low, but as soon as a second tab opens, CPU goes crazy.

I'll investigate.

**Comment by paulrouget** [comment]
It's because our rAF loop never stop.

STR:
- open example.com. normal CPU usage. rAF not running anymore.
- open another tab with example.com. high CPU usage. rAF looping.

**Comment by Gozala** [comment]
@paulrouget Ok so I looked into it a little bit and as far as I can tell there is constant update loop happening on servo, but not on gecko with a same two tabs loaded (I use `data:text/html,1` and `data:text/html,2`) it seems that something is not ending a loop correctly on servo which is surprising.

Anyway I'll add more logs to get a better idea what's going on.

**Comment by Gozala** [comment]
Here is what I've got by logging every action that enters update loop:

````
{"type":"WebViews","source":{"type":"WebView","id":"1","action":{"type":"Progress","action":{"type":"Tick","time":42323.343866}}}}
<<< Model:
[object Object]
<<< Effects:
[object Object]
Render took 20.762282999996387ms & will cause frame drop
>>> Action:
{"type":"WebViews","source":{"type":"WebView","id":"1","action":{"type":"Progress","action":{"type":"Tick","time":42342.891384}}}}
<<< Model:
[object Object]
<<< Effects:
[object Object]
>>> Action:
{"type":"WebViews","source":{"type":"WebView","id":"1","action":{"type":"Progress","action":{"type":"Tick","time":42367.562058}}}}
<<< Model:
[object Object]
<<< Effects:
[object Object]
Render took 30.132173000005423ms & will cause frame drop
>>> Action:
{"type":"WebViews","source":{"type":"WebView","id":"1","action":{"type":"Progress","action":{"type":"Tick","time":42378.881593}}}}
<<< Model:
[object Object]
<<< Effects:
[object Object]
>>> Action:
{"type":"WebViews","source":{"type":"WebView","id":"1","action":{"type":"Progress","action":{"type":"Tick","time":42412.845369}}}}
<<< Model:
[object Object]
<<< Effects:
[object Object]
>>> Action:
{"type":"WebViews","source":{"type":"WebView","id":"1","action":{"type":"Progress","action":{"type":"Tick","time":42425.716178}}}}
<<< Model:
[object Object]
<<< Effects:
[object Object]
>>> Action:
{"type":"WebViews","source":{"type":"WebView","id":"1","action":{"type":"Progress","action":{"type":"Tick","time":42441.613006}}}}
<<< Model:
[object Object]
<<< Effects:
[object Object]
>>> Action:
{"type":"WebViews","source":{"type":"WebView","id":"1","action":{"type":"Progress","action":{"type":"Tick","time":42462.455443}}}}
```

Looks like progress fails to end, still surprising how is it only a case on servo

**Comment by Gozala** [comment]
Alright I know what's going on, will make a patch & explain it in a bit

**Comment by Gozala** [comment]
@paulrouget attached pull fixes the issue and has details explaining what was actually going on. Now that being said I still have no idea how or why on servo we end up receiving additional tick, it is especially interesting to know why it does not happen with a single tab.

I also don't think that servo is just calling raf callback twice, because even if it did that still would not explain the issue as we do manage our tick handlers and second call would not have any more tick handlers to call (see https://github.com/Gozala/reflex/blob/master/src/effects.js#L161-L206)

Anyway I don't want to follow this rabbit hole, although potentially it could lead to discovery to other perf issues.

**Comment by paulrouget** [comment]
> Anyway I don't want to follow this rabbit hole, although potentially it could lead to discovery to other perf issues.

Absolutely. I will investigate.
