### ISSUE TITLE
Remove the HTTP server

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#979]
The http server is not useful. Servo can open local files. Furthermore, when we will package servo, we won't be using a HTTP server, so i'd prefer to not use http in our development process to be closer to the in-production configuration.

**Comment by Gozala** [comment]
live-reload feature is very helpful tool for my development process, I would really prefer not to loose that. That being said there maybe a configuration where we could keep server just for live-reload signaling.

**Comment by paulrouget** [comment]
> live-reload feature is very helpful tool for my development process

Does this require a http server?

**Comment by Gozala** [comment]
> Does this require a http server?

Well something needs to tell JS app to hot swap it's code, right now it's done by signaling from http server.

**Comment by Gozala** [comment]
Closing this for now!
