### ISSUE TITLE
Reintroduce scrolloutable titlebar

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#982]
Requires scrollgrab.

See https://github.com/servo/servo/issues/7672

**Comment by paulrouget** [comment]
Won't be happening because of https://github.com/servo/servo/issues/10434

**Comment by Gozala** [comment]
Alternatively we could do it with [wheel](https://developer.mozilla.org/en-US/docs/Web/Events/wheel) but they don't seem implemented in servo either servo/servo#11435

**Comment by paulrouget** [comment]
> Alternatively we could do it with wheel but they don't seem implemented in servo either servo/servo#11435

I think we can be a lot smarter about this. If we still want to do that, let's talk with @pcwalton about the proper way to implement it. I'm pretty sure it's super easy to do in Servo. The only real blocker for this is the not-perfect support for `overflow:scroll`. I need to spend some time to test the recent work @pcwalton  did to support `overflow:scroll`.

**Comment by Gozala** [comment]
I wonder if #1247 could provide an alternative way to go about it ? Or possibly a wheel events servo/servo#11435 could be yet another option ?

**Comment by paulrouget** [comment]
The proper way of doing is to be able to move the toolbar in the compositor based on the content scroll position. We want to achieve iOS-like animations (see toolbar animation in Safari).

To do so, we need to be able to transform the titlebar's div based on the content scroll position.

No specification allow us to fully do that yet, but the Houdini is close enough.

I'm working on [a draft](https://github.com/paulrouget/servo-embedding-api/blob/f53b8ca9aed60e5c724c9bf32b15fbaab19d3e2f/webidls/viewport.webidl#L6) that describes a mechanism that is based on existing spec (CompositorWorker), with extra accelerated properties to represent the content bounding box (this draft is far from being final, don't review it yet).

With such a mechanism, no need for scrollgrab, scrollsnapping, gestures or scroll events.

**Comment by Gozala** [comment]
@paulrouget That sounds like a long term project that would give us an ideal solution. I think we still want something in the meantime that may not be perfect but usable.
