### ISSUE TITLE
searchParams fails with Servo (and maybe webkit?)

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#985]
Servo now includes `searchParams`, but it fails with: `searchParams[Symbol.iterator] is not a function`. Maybe because it's an older spidermonkey. Not sure.

Anyway, this also appears to fail with Chrome:

```js
var searchParams = new URL("http:x.com/?x=y").searchParams;
for (var p of searchParams) {
  console.log(p);
}
```

**Comment by tschneidereit** [comment]
I think `Symbol.iterator` was introduced shortly after Servo's current SpiderMonkey was branched. But even if it did exist, support for using it on `URLSearchParams` instances wouldn't necessarily exist. And indeed, that was [added in Firefox 44 and Chrome 49](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#Browser_compatibility).

**Comment by Gozala** [comment]
There seem to be a different issue on chrome and servo. Chrome does not seem to have window.URLSearchParams in first place, which throws error on `window.URLSearchParams()` as of servo it's what @paul explained.

What makes things more complicated is [`URLSearchParams`](that https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) & all it's methods do return iterators :/

I'll try to workaround this somehow

**Comment by Gozala** [comment]
@tschneidereit @paulrouget Looking at the [`URLSearchParams` interface spec](https://url.spec.whatwg.org/#urlsearchparams) I don't see any other way to iterate over entries other than with `for of `. Maybe I should just always parse `url.search` myself instead ?
