### ISSUE TITLE
Rename record&replay

### ISSUE THREAD

**Issue by tschneidereit** [browserhtml/browserhtml#998]
Perhaps to something like store/load state, or take/restore snapshot.

The issue is that record&replay sounds a lot like the stuff `rr` is doing or that bhackett is working on for [WebReplay](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/WebReplay): like it's not about a single state but a series of actions that are deterministically replayed after recording.

@Gozala, does that make sense?

**Comment by tschneidereit** [comment]
After talking to @Gozala, I agree that we should keep this as-is.

**Comment by Gozala** [comment]
To be more more specific we plan on doing stuff like deterministic replay it's just first iteration that does not have it yet.
